(function(g){var window=this;var vW=function(a,b){var c=g.D(b);if(c){var d=g.Z(a,"toggled");c=g.M(d,c);(0,g.E)(c,function(e){g.T(e,d);e.removeAttribute("aria-pressed")})}},wW=function(a){try{return!!a&&null!=a.location.href&&g.Vc(a,"foo")}catch(b){return!1}},xW=function(a){g.ud(this,a,0,null,null)},Goa=function(){var a=yW(g.re),b=zW();
this.N=a;this.pubWin=b;this.C=(this.iframeWin=g.re)||{};this.D=-1;this.H=!1;this.L="";this.G=this.F=0},AW=function(a){a=void 0===a?g.q:a;
var b=a.context||a.AMP_CONTEXT_DATA;if(!b)try{b=a.parent.context||a.parent.AMP_CONTEXT_DATA}catch(c){}try{if(b&&b.pageViewId&&b.canonicalUrl)return b}catch(c){}return null},Hoa=function(a){g.q.google_image_requests||(g.q.google_image_requests=[]);
var b=g.q.document.createElement("img");b.src=a;g.q.google_image_requests.push(b)},Ioa=function(a){return g.qe(a,"object")},BW=function(a){return g.qe(a,"function")},CW=function(a,b){if(a)for(var c in a)Object.prototype.hasOwnProperty.call(a,c)&&b.call(void 0,a[c],c,a)},DW=function(a){return!(!a||!a.call)&&BW(a)},Joa=function(a,b){var c=b.slice(-1),d="?"===c||"#"===c?"":"&",e=[b];
CW(a,function(f,k){if(f||0===f||!1===f)g.qe(f,"boolean")&&(f=f?1:0),e.push(d),e.push(k),e.push("="),e.push(encodeURIComponent(String(f))),d="&"});
return e.join("")},zW=function(){if(g.po&&!wW(g.qo)){var a="."+g.ko.domain;
try{for(;2<a.split(".").length&&!wW(g.qo);)g.ko.domain=a=a.substr(a.indexOf(".")+1),g.qo=window.parent}catch(b){}wW(g.qo)||(g.qo=window)}return g.qo},Koa=function(){var a,b=window.ActiveXObject;
if(navigator.plugins&&navigator.mimeTypes.length){if((a=navigator.plugins["Shockwave Flash"])&&a.description)return a.description.replace(/([a-zA-Z]|\s)+/,"").replace(/(\s)+r/,".")}else{if(navigator.userAgent&&0<=navigator.userAgent.indexOf("Windows CE")){var c=3;for(a=1;a;)try{a=new b("ShockwaveFlash.ShockwaveFlash."+(c+1)),c++}catch(d){a=null}return c.toString()}if(g.Zb()){a=null;try{a=new b("ShockwaveFlash.ShockwaveFlash.7")}catch(d){c=0;try{a=new b("ShockwaveFlash.ShockwaveFlash.6"),c=6,a.AllowScriptAccess=
"always"}catch(e){if(6===c)return c.toString()}try{a=new b("ShockwaveFlash.ShockwaveFlash")}catch(e){}}if(a)return c=a.GetVariable("$version").split(" ")[1],c.replace(/,/g,".")}}return"0"},yW=function(a){a=a.top;
return wW(a)?a:null},EW=function(a,b){for(var c=0,d=a,e=0;a&&a!=a.parent;)if(a=a.parent,e++,wW(a))d=a,c=e;
else if(b)break;return{tg:d,level:c}},GW=function(){FW||(FW=EW(g.q,!0).tg);
return FW},Loa=function(a,b){CW(a,function(c,d){b[d]=c})},HW=function(a){var b=a.location.href;
if(a==a.top)return{url:b,Qk:!0};var c=!1,d=a.document;d&&d.referrer&&(b=d.referrer,a.parent==a.top&&(c=!0));(a=a.location.ancestorOrigins)&&(a=a[a.length-1])&&-1==b.indexOf(a)&&(c=!1,b=a);return{url:b,Qk:c}},Moa=function(){var a=zW();
if(a==a.top)return 0;for(;a&&a!=a.top&&wW(a);a=a.parent){if(a.sf_)return 2;if(a.$sf)return 3;if(a.inGptIF)return 4;if(a.inDapIF)return 5}return 1},Ooa=function(a){return(0,g.In)(Noa,function(b){return b.test(a)})},IW=function(a){if(a=/[-\w]+\.[-\w]+$/.exec(a))switch(g.sc(a[0].toLowerCase())){case 1967261364:return 0;
case 3147493546:return 1;case 1567346461:return 2;case 2183041838:return 3;case 763236279:return 4;case 1342279801:return 5;case 526831769:return 6;case 352806002:return 7;case 2755048925:return 8;case 3306848407:return 9;case 2207000920:return 10;case 484037040:return 11;case 3506871055:return 12;case 672143848:return 13;case 2528751226:return 14;case 2744854768:return 15;case 3703278665:return 16;case 2014749173:return 17;case 133063824:return 18;case 2749334602:return 19;case 3131239845:return 20;
case 2074086763:return 21;case 795772493:return 22;case 290857819:return 23;case 3035947606:return 24;case 2983138003:return 25;case 2197138676:return 26;case 4216016165:return 27;case 239803524:return 28;case 975993579:return 29;case 1794940339:return 30;case 1314429186:return 31;case 1643618937:return 32;case 497159982:return 33;case 3882239661:return 34}return-1},JW=function(a){if(!a.length)return 0;
for(var b=[],c=0;34>=c;c++)b[c]=0;for(c=a.length-1;0<=c;c--){var d=IW(a[c]);0<=d&&(b[34-d]=1)}return parseInt(b.join(""),2)},KW=function(a,b,c){this.url=a;
this.tg=b;this.hp=!!c;this.depth=null},LW=function(a){var b=a||g.q,c=[],d=null;
do{var e=b;if(wW(e)){var f=e.location.href;d=e.document&&e.document.referrer||null}else f=d,d=null;c.push(new KW(f||"",e));try{b=e.parent}catch(k){b=null}}while(b&&e!=b);e=0;for(b=c.length-1;e<=b;++e)c[e].depth=b-e;e=a||g.q;if(e.location&&e.location.ancestorOrigins&&e.location.ancestorOrigins.length==c.length-1)for(a=1;a<c.length;++a)b=c[a],b.url||(b.url=e.location.ancestorOrigins[a-1]||"",b.hp=!0);return c},MW=function(a){a=(this.F=a||g.q)||g.q;
this.D=a.top==a?1:wW(a.top)?2:3;3!=this.D&&(this.lastModifiedTime=Date.parse(g.q.top.document.lastModified)/1E3);this.C=LW(this.F)},OW=function(a){for(var b=[],c=Math.min(a.C.length,27),d=1;d<c;d++)a.C[d]&&a.C[d].url&&(b[d-1]=a.C[d].url);
return NW(a,b.reverse())},PW=function(a){var b=a.F.document&&a.F.document.scripts?a.F.document.scripts:[];
if(!b)return 0;for(var c=[],d=b.length-1;0<=d&&26>c.length;)b[d].src&&c.unshift(b[d].src),d--;return NW(a,c)},NW=function(a,b){for(var c,d=0,e=(c=a.C[Math.max(a.C.length-1,0)].url||null)&&g.yc(c),f=Math.min(b.length,26),k=0;k<f;k++)c=null!=b[k]&&g.yc(b[k])||"",d*=4,c&&(e&&c==e?d+=3:Ooa(b[k])?d+=2:c&&0<=IW(c)&&(d+=1));
return d},QW=function(a){a=a.C;
for(var b=[],c=a.length-1;0<c;c--){var d=a[c];d&&null!=d.url&&b.push(g.yc(d.url))}return JW(b)},RW=function(a){a=a.F.document&&a.F.document.scripts?a.F.document.scripts:[];
if(!a)return 0;for(var b=[],c=a.length-1;0<=c;c--){var d=a[c];d&&null!=d.src&&b.push(g.yc(d.src))}return JW(b)},Poa=function(a,b){this.C=a;
this.F=b},Roa=function(){if(!g.Tg("disable_ad_status_on_html5_clients")&&(!g.Tg("condition_ad_status_fetch_on_consent_cookie_html5_clients")||g.Li("CONSENT","").startsWith("YES+"))&&"1"!=g.lp(g.H("PLAYER_CONFIG",{}),"args","privembed")){var a=function(){SW=!0;
"google_ad_status"in window?g.Pg("DCLKSTAT",1):g.Pg("DCLKSTAT",2)};
g.ik("//static.doubleclick.net/instream/ad_status.js",a);Qoa.push(g.uh(function(){if(!(SW||"google_ad_status"in window)){var b=g.hk("//static.doubleclick.net/instream/ad_status.js");spf.script.ignore(b,a);SW=!0;g.Pg("DCLKSTAT",3)}},5E3))}},Soa=function(a){a=a.target.result;
a.objectStoreNames.contains("swpushnotificationsstore")&&a.deleteObjectStore("swpushnotificationsstore");a.createObjectStore("swpushnotificationsstore",{keyPath:"key"})},UW=function(){return TW?Promise.resolve(TW):new Promise(function(a,b){var c=self.indexedDB.open("swpushnotificationsdb");
c.onerror=b;c.onsuccess=function(){var d=c.result;if(d.objectStoreNames.contains("swpushnotificationsstore"))TW=d,a(TW);else return self.indexedDB.deleteDatabase("swpushnotificationsdb"),UW()};
c.onupgradeneeded=Soa})},Toa=function(){var a=new g.Vj("Error accessing DB");
return UW().then(function(b){return new Promise(function(c,d){try{var e=b.transaction("swpushnotificationsstore").objectStore("swpushnotificationsstore").get("WatchCount");e.onsuccess=function(){var f=e.result;c(f?f.value:null)};
e.onerror=function(){a.params={key:"WatchCount",source:"onerror"};d(a)}}catch(f){a.params={key:"WatchCount",
thrownError:String(f)},d(a)}})},function(){return null})},Uoa=function(a){var b={key:"WatchCount"};
b.value=a;UW().then(function(c){return new Promise(function(d,e){try{var f=c.transaction("swpushnotificationsstore","readwrite").objectStore("swpushnotificationsstore").put(b);f.onsuccess=function(){d()};
f.onerror=function(){e()}}catch(k){e(k)}})})},Voa=function(){var a=new MW(g.re),b=a.C[0].depth,c={};
c=(c.dssz=g.ko.scripts?g.ko.scripts.length:0,c.icsg=PW(a),c.mdo=QW(a),c.mso=RW(a),c);g.re.location&&g.re.location.ancestorOrigins&&(c.iag=OW(a));0<b&&(c.nhd=b);return c},Woa=function(a){var b;
g.As(["fullscreenEnabled","webkitFullscreenEnabled","mozFullScreenEnabled","msFullscreenEnabled"],document)?g.vx()==a&&(b=document):b=a;if(b&&(a=g.As(["exitFullscreen","webkitExitFullscreen","mozCancelFullScreen","msExitFullscreen"],b))){a.call(b)instanceof Promise||Promise.resolve();return}Promise.resolve()},Xoa=function(a){return(0,g.Hn)(a,function(b){return{key:b.id,
name:b.name}})},VW=function(){var a=g.fz("yt-remote-cast-receiver");
return a?a.friendlyName:null},Yoa=function(){var a=g.QA().Cc.$_gos();
var b=g.YA();b&&g.aB()&&(g.Xy(a,b)||a.push(b));return Xoa(a)},Zoa=function(){var a=Yoa(),b=g.YA();
b||(b=g.VA());return g.Ua(a,function(c){return b&&g.Ry(b,c.key)?!0:!1})},WW=function(){var a=Zoa();
!a&&g.gA()&&VW()&&(a={key:"cast-selector-receiver",name:VW()});return a},XW=function(){var a=g.D("watch-queue-mole");
return!!a&&g.lx(a)},YW=function(){var a=g.D("watch-queue-mole");
return a&&g.Sq(a)?0:1},$oa=function(a){if(!a||g.wb(a.responseText))g.cN();
else try{eval(a.responseText)}catch(b){throw g.cN(),b;}},apa=function(){var a={};
return a.dff="times new roman",a.dfs="16",a.ppjl="u",a.rsz="||n|",a},ZW=function(a){var b=g.oi(g.ni);
g.Oo(b,g.pi(g.ni));g.Tg("desktop_pyv_on_watch_missing_params")&&(g.Oo(b,apa()),g.Oo(b,Voa()));a=g.Fc(a,b);g.Tg("desktop_pyv_on_watch_override_lact")&&(a=g.eq(a,"lact",g.Dh()));g.WM=g.K(a,{format:"RAW",onSuccess:$oa,onError:function(){g.cN()},
withCredentials:!0});g.zm("parq")},$W=function(a,b){if(!a)return!1;
var c=a.hash;if(!c||!c.indexOf)return!1;if(-1!=c.indexOf(b))return!0;var d=bpa(b);return"go"!=d&&-1!=c.indexOf(d)?!0:!1},bpa=function(a){var b="";
CW(a.split("_"),function(c){b+=c.substr(0,2)});
return b},aX=function(){this.C=function(a){return void 0===a?!1:a}},bX=function(){var a=void 0===a?!1:a;
return aX.getInstance().C(a)},cX=function(a,b){var c;
if("relative"===a)return b;c||(c="https");g.q.location&&"https:"==g.q.location.protocol&&"http"==c&&(c="https");return[c,"://",a,b].join("")},cpa=function(a){var b=a.C;
null==b.google_ad_output&&(b.google_ad_output="html");if(null!=b.google_ad_client){var c;(c=String(b.google_ad_client))?(c=c.toLowerCase())&&"ca-"!=c.substring(0,3)&&(c="ca-"+c):c="";b.google_ad_client=c}null!=b.google_ad_slot&&(b.google_ad_slot=String(b.google_ad_slot));if(null==b.google_flash_version){try{var d=Koa()}catch(e){d="0"}b.google_flash_version=d}b.google_webgl_support=!!g.re.WebGLRenderingContext;b.google_ad_section=b.google_ad_section||b.google_ad_region||"";b.google_country=b.google_country||
b.google_gl||"";d=(new Date).getTime();Array.isArray(b.google_color_bg)&&(b.google_color_bg=dX(a,b.google_color_bg,d));Array.isArray(b.google_color_text)&&(b.google_color_text=dX(a,b.google_color_text,d));Array.isArray(b.google_color_link)&&(b.google_color_link=dX(a,b.google_color_link,d));Array.isArray(b.google_color_url)&&(b.google_color_url=dX(a,b.google_color_url,d));Array.isArray(b.google_color_border)&&(b.google_color_border=dX(a,b.google_color_border,d));Array.isArray(b.google_color_line)&&
(b.google_color_line=dX(a,b.google_color_line,d))},hX=function(){var a=window;
CW(eX,function(b,c){a[c]=null});
CW(fX,function(b,c){a[c]=null});
CW(gX,function(b,c){a[c]=null});
a.google_container_id=null;a.google_page_location=null;a.google_referrer_url=null;a.google_enable_single_iframe=null;a.google_ad_region=null;a.google_gl=null;a.google_loader_used=null;a.google_loader_features_used=null;a.google_debug_params=null},dX=function(a,b,c){a.F|=2;
return b[c%b.length]},iX=function(a,b){var c=void 0===c?{}:c;
this.error=a;this.context=b.context;this.msg=b.message||"";this.id=b.id||"jserror";this.meta=c},jX=function(){this.D="&";
this.G=!1;this.F={};this.H=0;this.C=[]},kX=function(a,b){var c={};
c[a]=b;return[c]},mX=function(a,b,c,d,e){var f=[];
g.ie(a,function(k,l){var m=lX(k,b,c,d,e);m&&f.push(l+"="+m)});
return f.join(b)},lX=function(a,b,c,d,e){if(null==a)return"";
b=b||"&";c=c||",$";"string"==typeof c&&(c=c.split(""));if(a instanceof Array){if(d=d||0,d<c.length){for(var f=[],k=0;k<a.length;k++)f.push(lX(a[k],b,c,d+1,e));return f.join(c[d])}}else if("object"==typeof a)return e=e||0,2>e?encodeURIComponent(mX(a,b,c,d,e+1)):"...";return encodeURIComponent(String(a))},nX=function(a,b,c,d){a.C.push(b);
a.F[b]=kX(c,d)},dpa=function(a){var b=1,c;
for(c in a.F)b=c.length>b?c.length:b;return 3997-b-a.D.length-1},oX=function(a,b,c,d,e){if((d?a.C:Math.random())<(e||.01))try{if(c instanceof jX)var f=c;
else f=new jX,g.ie(c,function(l,m){var n=f,r=n.H++,x=kX(m,l);n.C.push(r);n.F[r]=x});
var k=f.getUrl(a.F,"pagead2.googlesyndication.com","/pagead/gen_204?id="+b+"&","");k&&Hoa(k)}catch(l){}},pX=function(){var a=g.q.performance;
return a&&a.now&&a.timing?Math.floor(a.now()+a.timing.navigationStart):(0,g.Od)()},qX=function(){var a=void 0===a?g.q:a;
return(a=a.performance)&&a.now?a.now():null},epa=function(a,b,c){this.label=a;
this.type=b;this.value=c;this.duration=0;this.uniqueId=Math.random();this.slotId=void 0},tX=function(){var a=rX;
this.events=[];this.F=a||g.q;var b=null;a&&(a.google_js_reporting_queue=a.google_js_reporting_queue||[],this.events=a.google_js_reporting_queue,b=a.google_measure_js_timing);this.C=sX()||(null!=b?b:1>Math.random())},vX=function(a){a&&uX&&sX()&&(uX.clearMarks("goog_"+a.label+"_"+a.uniqueId+"_start"),uX.clearMarks("goog_"+a.label+"_"+a.uniqueId+"_end"))},yX=function(){var a=wX;
this.H=xX;this.F=null;this.L=this.G;this.C=void 0===a?null:a;this.D=!1},fpa=function(a,b,c){try{if(a.C&&a.C.C){var d=a.C.start(b.toString(),3);
var e=c();a.C.end(d)}else e=c()}catch(k){c=!0;try{vX(d);var f=new iX(k,{message:zX(k)});c=a.L(b,f,void 0,void 0)}catch(l){a.G(217,l)}if(!c)throw k;}return e},gpa=function(a,b){var c=AX;
return function(d){for(var e=[],f=0;f<arguments.length;++f)e[f-0]=arguments[f];return fpa(c,a,function(){return b.apply(void 0,e)})}},zX=function(a){var b=a.toString();
a.name&&-1==b.indexOf(a.name)&&(b+=": "+a.name);a.message&&-1==b.indexOf(a.message)&&(b+=": "+a.message);if(a.stack){a=a.stack;var c=b;try{-1==a.indexOf(c)&&(a=c+"\n"+a);for(var d;a!=d;)d=a,a=a.replace(/((https?:\/..*\/)[^\/:]*:\d+(?:.|\n)*)\2/,"$1");b=a.replace(/\n */g,"\n")}catch(e){b=c}}return b},BX=function(a,b){return gpa(a,b)},hpa=function(){this.wasPlaTagProcessed=!1;
this.wasReactiveAdConfigReceived={};this.adCount={};this.wasReactiveAdVisible={};this.stateForType={};this.reactiveTypeEnabledInAsfe={};this.wasReactiveTagRequestSent=!1;this.reactiveTypeDisabledByPublisher={};this.tagSpecificState={};this.improveCollisionDetection=1;this.messageValidationEnabled=!1;this.floatingAdsStacking=new CX},DX=function(a){a.google_reactive_ads_global_state?null==a.google_reactive_ads_global_state.floatingAdsStacking&&(a.google_reactive_ads_global_state.floatingAdsStacking=
new CX):a.google_reactive_ads_global_state=new hpa;
return a.google_reactive_ads_global_state},CX=function(){this.maxZIndexRestrictions={};
this.nextRestrictionId=0;this.maxZIndexListeners=[]},EX=function(a){return a!=a.top?512:0},GX=function(a,b){var c=FX(a).clientWidth;
return c?c>(void 0===b?420:b)?32768:320>c?65536:0:16384},HX=function(a){var b=FX(a).clientWidth;
a=a.innerWidth;return(b=b&&a?b/a:0)?1.05<b?262144:.95>b?524288:0:131072},FX=function(a){a=a.document;
var b={};a&&(b="CSS1Compat"==a.compatMode?a.documentElement:a.body);return b||{}},ipa=function(a,b){if(!a.adCount)return!1;
if(1==b||2==b)return!(!a.adCount[1]&&!a.adCount[2]);var c=a.adCount[b];return c&&27!==b&&26!==b&&10!==b?1<=c:!1},IX=function(){this.C=function(){return[]}},jpa=function(){this.S={}},LX=function(){if(JX)return JX;
var a=KX(),b=a.google_persistent_state_async;return null!=b&&"object"==typeof b&&null!=b.S&&"object"==typeof b.S?JX=b:a.google_persistent_state_async=JX=new jpa},MX=function(a,b,c){b=kpa[b]||"google_ps_"+b;
a=a.S;var d=a[b];return void 0===d?a[b]=c:d},KX=function(){var a=AW();
return(a?wW(a.master)?a.master:null:null)||zW()},lpa=function(){try{return NX.javaEnabled()}catch(a){return!1}},OX=function(a){var b=1,c;
if(void 0!=a&&""!=a)for(b=0,c=a.length-1;0<=c;c--){var d=a.charCodeAt(c);b=(b<<6&268435455)+d+(d<<14);d=b&266338304;b=0!=d?b^d>>21:b}return b},PX=function(a,b){if(!a||"none"==a)return 1;
a=String(a);"auto"==a&&(a=b,"www."==a.substring(0,4)&&(a=a.substring(4,a.length)));return OX(a.toLowerCase())},QX=function(a,b,c){a-=b;
return a>=(void 0===c?1E5:c)?"M":0<=a?a:"-M"},SX=function(a){a=a.google_reactive_ad_format;
return g.ip(RX,a)?""+a:null},TX=function(a){return!!SX(a)||null!=a.google_pgb_reactive},UX=function(a,b){var c;
a:{for(c=0;c<b.length;c++){var d=a;var e=b[c];var f=d.document;f.elementFromPoint(e.x,e.y);var k=e.x;e=e.y;f.hasOwnProperty("_goog_efp_called_")||(f._goog_efp_called_=f.elementFromPoint(k,e));if(f=f.elementFromPoint(k,e))if("fixed"==g.Cr(f))d=f;else{c:{d=d.document;for(f=f.offsetParent;f&&f!=d.body;f=f.offsetParent)if("fixed"==g.Cr(f)){d=f;break c}d=null}d=d?d:null}else d=null;if(d){c=d;break a}}c=null}return null!=c},VX=function(a,b,c){for(var d=[],e=0;3>e;e++)for(var f=0;3>f;f++)d.push({x:f/2*(a-
0),
y:b+e/2*(c-b)});return d},mpa=function(a){try{a.setItem("__storage_test__","__storage_test__");
var b=a.getItem("__storage_test__");a.removeItem("__storage_test__");return"__storage_test__"==b}catch(c){return!1}},WX=function(a){try{if(null==a||!mpa(a))return null;
var b=a.getItem("__lsv__");if(!b)return[];try{var c=JSON.parse(b)}catch(d){}return!Array.isArray(c)||(0,g.In)(c,function(d){return!Number.isInteger(d)})?(a.removeItem("__lsv__"),[]):npa(c)}catch(d){return null}},npa=function(a){a=void 0===a?[]:a;
var b=Date.now();return(0,g.Nm)(a,function(c){return 36E5>b-c})},XX=function(a){return!!a&&1>a.length},ppa=function(a,b,c,d){switch(c){case 0:return 0;
case 1:case 2:var e=void 0===e?opa:e;d=0;try{d|=EX(a);var f=Math.min(a.screen.width||0,a.screen.height||0);d|=f?320>f?8192:0:2048;var k;if(k=a.navigator){var l=a.navigator.userAgent;k=/Firefox/.test(l)||/Android 2/.test(l)||/iPhone OS [34]_/.test(l)||/Windows Phone (?:OS )?[67]/.test(l)}d|=k?1048576:0}catch(x){d|=32}var m=0;try{m|=a.innerHeight>=a.innerWidth?0:8,m|=GX(a,e),m|=HX(a)}catch(x){m|=32}e=!1;if(!bX()){switch(c){case 2:c=VX(a.innerWidth,0,Math.round(a.innerWidth/320*50+15));e=UX(a,c);break;
case 1:if(c=bX())c=a.innerHeight,c=VX(a.innerWidth,c-Math.round(a.innerWidth/320*50+15),c),c=UX(a,c);e=c}e&&(m|=16777216)}return d|m;case 8:c=!("on"===b.google_adtest||$W(a.location,"google_ia_debug"));e=0;try{e|=EX(a),e|=a.navigator&&/Android 2/.test(a.navigator.userAgent)?1048576:0}catch(x){e|=32}var n=0;try{n|=GX(a,2500),bX()&&(m=FX(a).clientHeight,n|=m?320>m?-2147483648:0:1073741824),n|=HX(a),c&&!XX(WX(d))&&(n|=134217728)}catch(x){n|=32}return e|n;case 9:c=bX()&&!("on"===b.google_adtest||$W(a.location,
"google_scr_debug"));m=0;try{m|=EX(a),m|=HX(a),m|=GX(a),m|=a.innerHeight>=a.innerWidth?0:8,m|=a.navigator&&/Android 2/.test(a.navigator.userAgent)?1048576:0,c&&!XX(WX(d))&&(m|=134217728)}catch(x){m|=32}return m;case 16:return b.google_ad_resizable&&!b.google_reactive_ad_format&&a.navigator&&/iPhone|iPod|iPad|Android|BlackBerry/.test(a.navigator.userAgent)&&a.top==a?0:8388608;case 30:d=0;try{d|=EX(a);d|=a.getComputedStyle?0:2097152;!(g.Yb("iPad")||g.Yb("Android")&&!g.Yb("Mobile")||g.Yb("Silk"))&&(g.Yb("iPod")||
g.Yb("iPhone")||g.Yb("Android")||g.Yb("IEMobile"))||(d|=1048576);1200>=Math.floor(a.document.body.getBoundingClientRect().width)||(d|=32768);a:{var r=a.document.getElementsByClassName("adsbygoogle");for(a=0;a<r.length;a++)if("autorelaxed"==g.Bv(r[a],"adFormat")){n=!0;break a}n=!1}n&&(d|=33554432)}catch(x){d|=32}return d;case 26:d=0;try{d|=EX(a),d|=a.getComputedStyle?0:2097152,d|=a.document.querySelectorAll&&a.document.querySelector?0:4194304,d|=GX(a,1E4)}catch(x){d|=32}return d;case 27:d=0;try{d|=
EX(a),d|=a.getComputedStyle?0:2097152,d|=GX(a,1E4)}catch(x){d|=32}return d;default:return 32}},spa=function(a){if(!a.hash)return null;
var b=null;CW(qpa,function(c){!b&&$W(a,c)&&(b=rpa[c])});
return b},vpa=function(a,b,c){if(!b)return null;
var d=DX(b),e=0;CW(RX,function(f){var k=tpa[f];k&&0===upa(a,b,f,c)&&(e|=k)});
d.wasPlaTagProcessed&&(e|=256);a.google_reactive_tag_first&&(e|=1024);return e?""+e:null},upa=function(a,b,c,d){if(!b)return 256;
var e=0,f=DX(b),k=ipa(f,c);if(a.google_reactive_ad_format==c||26!=c&&27!=c&&k)e|=64;var l=!1;CW(f.reactiveTypeDisabledByPublisher,function(m,n){String(c)===n&&(l=!0)});
l&&spa(b.location)!==c&&(e|=128);return e|ppa(b,a,c,d)},YX=function(a){this.G=[];
this.F=a||window;this.C=0;this.D=null;this.H=0},ZX=function(a){var b=BX(189,(0,g.v)(a.sG,a));
a.F.setTimeout(b,0)},$X=function(a){try{return a.sz()}catch(b){return!1}},aY=function(a,b){this.mc=a;
this.tg=b},bY=function(a,b){b=void 0===b?window:b;
if(g.kq(a,5))try{return b.localStorage}catch(c){}return null},cY=function(a,b){b=void 0===b?document:b;
return g.kq(a,5)?b.cookie:null},dY=function(a,b,c){c=void 0===c?document:c;
b=cY(b,c);return null===b?null:(new g.Jd({cookie:b})).get(a)||""},eY=function(a){this.C=a;
this.F=0},iY=function(){fY=g.q;
gY=fY.googleToken=fY.googleToken||{};var a=(0,g.Od)();gY[1]&&gY[3]>a&&0<gY[2]||(gY[1]="",gY[2]=-1,gY[3]=-1,gY[4]="",gY[6]="");hY=fY.googleIMState=fY.googleIMState||{};a=hY[1];wpa.test(a)&&!xpa.test(a)||(hY[1]=".google.com");Array.isArray(hY[5])||(hY[5]=[]);"boolean"!==typeof hY[6]&&(hY[6]=!1);Array.isArray(hY[7])||(hY[7]=[]);"number"!==typeof hY[8]&&(hY[8]=0)},Fpa=function(a){for(var b=a.getElementsByTagName("script"),c=b.length,d=0;d<c;++d){var e=b[d];
if(e.hasAttribute("src")){e=e.getAttribute("src");if(ypa.test(e))return 5;if(jY.test(e))return 6}}b=a.getElementsByTagName("link");c=b.length;for(d=0;d<c;++d)if(e=b[d],e.hasAttribute("href")&&(e=e.getAttribute("href"),zpa.test(e)||jY.test(e)))return 6;a=a.getElementsByTagName("meta");d=a.length;for(e=0;e<d;++e){var f=a[e];if("generator"==f.getAttribute("name")&&f.hasAttribute("content")){f=f.getAttribute("content");if(Apa.test(f))return 1;if(Bpa.test(f))return 2;if(Cpa.test(f))return 3;if(Dpa.test(f))return 4}}for(a=
0;a<c;++a)if(d=b[a],"stylesheet"==d.getAttribute("rel")&&d.hasAttribute("href")&&(d=d.getAttribute("href"),Epa.test(d)))return 2;return 0},Opa=function(a){if(!b){var b=new xW;
g.B(b,5,!0)}var c=a.C,d=zW().document,e={},f=zW();var k=EW(zW(),!1).tg;var l=HW(k);a:{var m=zW(),n=c.google_ad_width||m.google_ad_width,r=c.google_ad_height||m.google_ad_height;if(m&&m.top==m)var x=!1;else{var y=d.documentElement;if(n&&r){var C=1,S=1;m.innerHeight?(C=m.innerWidth,S=m.innerHeight):y&&y.clientHeight?(C=y.clientWidth,S=y.clientHeight):d.body&&(C=d.body.clientWidth,S=d.body.clientHeight);if(S>2*r||C>2*n){x=!1;break a}}x=!0}}var P=x;var pa=l.Qk,Ba=zW(),Ha=Ba.top==Ba?0:wW(Ba.top)?1:2,vc=
4;P||1!=Ha?P||2!=Ha?P&&1==Ha?vc=7:P&&2==Ha&&(vc=8):vc=6:vc=5;pa&&(vc|=16);var qi=""+vc;var ri=Moa();var eN=!!c.google_page_url;e.google_iframing=qi;0!=ri&&(e.google_iframing_environment=ri);if(!eN&&"ad.yieldmanager.com"==d.domain){for(var fu=d.URL.substring(d.URL.lastIndexOf("http"));-1<fu.indexOf("%");)try{fu=decodeURIComponent(fu)}catch(Vg){break}c.google_page_url=fu;eN=!!fu}eN?(e.google_page_url=c.google_page_url,e.google_page_location=(P?d.referrer:d.URL)||"EMPTY"):(P&&wW(f.top)&&d.referrer&&
f.top.document.referrer===d.referrer?e.google_page_url=f.top.document.URL:e.google_page_url=P?d.referrer:d.URL,e.google_page_location=null);if(d.URL===e.google_page_url)try{var fN=Math.round(Date.parse(d.lastModified)/1E3)||null}catch(Vg){fN=null}else fN=null;e.google_last_modified_time=fN;if(k==k.top)var a8=k.document.referrer;else{var b8=AW();a8=b8&&b8.referrer||""}e.google_referrer_url=a8;Loa(e,c);var iB=c.google_page_location||c.google_page_url;"EMPTY"==iB&&(iB=c.google_page_url);if(iB){var Wg=
iB.toString();0==Wg.indexOf("http://")?Wg=Wg.substring(7,Wg.length):0==Wg.indexOf("https://")&&(Wg=Wg.substring(8,Wg.length));var gN=Wg.indexOf("/");-1==gN&&(gN=Wg.length);var c8=Wg.substring(0,gN);if(Gpa.test(c8))var hN=!1;else{var Rp=c8.split("."),jB=!1;3<=Rp.length&&(jB=Rp[Rp.length-3]in kY);2<=Rp.length&&(jB=jB||Rp[Rp.length-2]in kY);hN=jB}}else hN=!1;var e8=hN?"pagead2.googlesyndication.com":"googleads.g.doubleclick.net",kB=b,oa={};Hpa(a,oa);iY();oa.adsid=gY[1];iY();oa.pucrd=gY[6];var iN=a.pubWin.google_user_agent_client_hint;
if(iN){for(var jN=[],f8=0,kN=0;kN<iN.length;kN++){var lB=iN.charCodeAt(kN);255<lB&&(jN[f8++]=lB&255,lB>>=8);jN[f8++]=lB}oa.uach=g.cd(jN,3)}var ig=a.C,gu=a.C;oa.dt=g.ti;gu.google_async_iframe_id&&gu.google_bpp&&(oa.bpp=gu.google_bpp);var rva=zW();b:{var sva=zW();try{var Sp=sva.performance;if(Sp&&Sp.timing&&Sp.now){var g8=Sp.timing.navigationStart+Math.round(Sp.now())-Sp.timing.domLoading;break b}}catch(Vg){}g8=null}var h8=g8;if(h8){var tva=rva.Date.now()-g.ti;var i8=QX(h8,tva,1E6)}else i8=null;var j8=
i8;j8&&(oa.bdt=j8);var k8=gu.google_iframe_start_time;if("number"!==typeof k8)var l8=null;else gu.google_iframe_start_time=null,l8=QX(k8,g.ti);var m8=l8;null!=m8&&(oa.fdt=m8);oa.idt=QX(0,g.ti);var mB=a.C;oa.shv="r20100101";oa.cbv="/r20100101".replace("/","");"sa"==mB.google_loader_used?oa.ptt=5:"aa"==mB.google_loader_used&&(oa.ptt=9);/^\w{1,3}$/.test(mB.google_loader_used)&&(oa.saldr=mB.google_loader_used);var lN=AW(a.pubWin);if(lN){oa.is_amp=1;var mN=lN||AW();oa.amp_v=mN&&mN.mode?+mN.mode.version||
null:null;var nN=lN||AW();if(nN&&nN.container){for(var n8=nN.container.split(","),o8=[],oN=0;oN<n8.length;oN++)o8.push(Ipa[n8[oN]]||"x");var p8=o8.join()}else p8=null;var q8=p8;q8&&(oa.act=q8)}zW()==window.top&&(oa.abxe=1);if("_gfp_a_"in a.pubWin){var pN=a.pubWin._gfp_a_;if("boolean"!==typeof pN)throw Error("Illegal value of _gfp_a_: "+pN);if(pN&&bX()){var r8;(r8=dY("__gads",kB,(new eY(a.pubWin)).C.document))&&(oa.cookie=r8)}}var Jk=LX(),s8=MX(Jk,8,{}),nB=ig.google_ad_section;s8[nB]&&(oa.prev_fmts=
s8[nB]);var t8=MX(Jk,9,{});t8[nB]&&(oa.prev_slotnames=t8[nB].toLowerCase());var qN=MX(Jk,8,{}),rN=MX(Jk,9,{}),Tp=ig.google_ad_section,sN=ig.google_ad_format,tN=ig.google_ad_slot;sN?qN[Tp]=qN[Tp]?qN[Tp]+(","+sN):sN:tN&&(rN[Tp]=rN[Tp]?rN[Tp]+(","+tN):tN);var u8=MX(Jk,15,0);0<u8&&(oa.nras=String(u8));var v8=zW(),w8=AW(v8);if(w8){var uN=w8||AW();if(uN){var x8=uN.pageViewId,y8=uN.clientId;"string"===typeof y8&&(x8+=y8.replace(/\D/g,"").substr(0,6));var z8=x8}else z8=null;var A8=+z8}else{var B8=EW(v8,!1).tg,
vN=B8.google_global_correlator;vN||(B8.google_global_correlator=vN=1+Math.floor(Math.random()*Math.pow(2,43)));A8=vN}oa.correlator=MX(Jk,7,A8);bX()&&(oa.rume=1);if(ig.google_ad_channel){for(var C8=MX(Jk,10,{}),D8="",F8=ig.google_ad_channel.split(lY),wN=0;wN<F8.length;wN++){var xN=F8[wN];C8[xN]?D8+=xN+"+":C8[xN]=!0}oa.pv_ch=D8}if(ig.google_ad_host_channel){for(var oB=MX(Jk,11,[]),G8=ig.google_ad_host_channel.split("|"),pB=-1,yN=[],Xi=0;Xi<G8.length;Xi++){var H8=G8[Xi].split(lY);oB[Xi]||(oB[Xi]={});
for(var hu="",zN=0;zN<H8.length;zN++){var qB=H8[zN];""!==qB&&(oB[Xi][qB]?hu+="+"+qB:oB[Xi][qB]=!0)}hu=hu.slice(1);yN[Xi]=hu;""!==hu&&(pB=Xi)}var AN="";if(-1<pB){for(var BN=0;BN<pB;BN++)AN+=yN[BN]+"|";AN+=yN[pB]}oa.pv_h_ch=AN}oa.frm=ig.google_iframing;oa.ife=ig.google_iframing_environment;var I8=ig.google_ad_client;try{var J8=GW(),rB=J8.google_prev_clients;rB||(rB=J8.google_prev_clients={});if(I8 in rB)var CN=1;else rB[I8]=!0,CN=2}catch(Vg){CN=0}oa.pv=CN;var DN=a.pubWin.document,K8=a.C,iu=cY(kB,DN)||
"";var L8=DN.domain,sB=a.pubWin.screen,vva=DN.referrer,wva=g.se();if(AW())var M8=zW().gaGlobal||{};else{var EN=Math.round((new Date).getTime()/1E3),FN=K8.google_analytics_domain_name,tB="undefined"==typeof FN?PX("auto",L8):PX(FN,L8),xva=-1<iu.indexOf("__utma="+tB+"."),yva=-1<iu.indexOf("__utmb="+tB),GN;if(!(GN=KX().gaGlobal)){var zva={};GN=KX().gaGlobal=zva}var nd=GN,N8=!1;if(xva){var HN=iu.split("__utma="+tB+".")[1].split(";")[0].split(".");yva?nd.sid=HN[3]+"":nd.sid||(nd.sid=EN+"");nd.vid=HN[0]+
"."+HN[1];nd.from_cookie=!0}else{nd.sid||(nd.sid=EN+"");if(!nd.vid){N8=!0;var Ava=Math.round(2147483647*Math.random()),O8=wva,P8,Dm=[NX.appName,NX.version,NX.language?NX.language:NX.browserLanguage,NX.platform,NX.userAgent,lpa()?1:0].join("");if(sB)Dm+=sB.width+"x"+sB.height+sB.colorDepth;else if(g.q.java&&g.q.java.awt){var Q8=g.q.java.awt.Toolkit.getDefaultToolkit().getScreenSize();Dm+=Q8.screen.width+"x"+Q8.screen.height}Dm=Dm+iu+(vva||"");for(P8=Dm.length;0<O8;)Dm+=O8--^P8++;nd.vid=(Ava^OX(Dm)&
2147483647)+"."+EN}nd.from_cookie=!1}if(!nd.cid){b:{var Up=FN,R8=999;Up&&(Up=0==Up.indexOf(".")?Up.substr(1):Up,R8=(""+Up).split(".").length);for(var S8,T8=999,uB=iu.split(";"),ju=0;ju<uB.length;ju++){var vB=Jpa.exec(uB[ju])||Kpa.exec(uB[ju])||Lpa.exec(uB[ju]);if(vB){var IN=vB[1]||0;if(IN==R8){var U8=vB[2];break b}IN<T8&&(T8=IN,S8=vB[2])}}U8=S8}var ku=U8;N8&&ku&&-1!=ku.search(/^\d+\.\d+$/)?(nd.vid=ku,nd.from_cookie=!0):ku!=nd.vid&&(nd.cid=ku)}nd.dh=tB;nd.hid||(nd.hid=Math.round(2147483647*Math.random()));
M8=nd}var lu=M8;oa.ga_vid=lu.vid;oa.ga_sid=lu.sid;oa.ga_hid=lu.hid;oa.ga_fc=lu.from_cookie;oa.ga_cid=lu.cid;oa.ga_wpids=K8.google_analytics_uacct;var mu=a.pubWin,nu=new MW(mu);mu.location&&mu.location.ancestorOrigins&&(oa.iag=OW(nu));oa.icsg=PW(nu);var JN=nu.C[0].depth;JN&&0<JN&&(oa.nhd=JN);oa.dssz=mu.document.scripts?mu.document.scripts.length:0;oa.mdo=QW(nu);oa.mso=RW(nu);var KN=ig.google_ad_layout;KN&&0<=mY[KN]&&(oa.rplot=mY[KN]);g.te(oa);var LN,W8=AW(),wB=W8&&W8.initialIntersection;if(LN=(wB&&
g.Ma(wB.rootBounds)?new g.Td(wB.rootBounds.width,wB.rootBounds.height):null)||g.ue(a.pubWin.top))oa.biw=LN.width,oa.bih=LN.height;var X8=a.pubWin;if(X8.top!=X8){var MN=g.ue(a.pubWin);MN&&(oa.isw=MN.width,oa.ish=MN.height)}var Em=a.pubWin;if(null!==Em&&Em!=Em.top){var xB=[Em.document.URL];Em.name&&xB.push(Em.name);var Y8=g.ue(Em,!1);xB.push(Y8.width.toString());xB.push(Y8.height.toString());var Z8=xB.join(""),$8=Z8.length;if(0==$8)var NN=0;else{for(var Vp=305419896,ON=0;ON<$8;ON++)Vp^=(Vp<<5)+(Vp>>
2)+Z8.charCodeAt(ON)&4294967295;NN=0<Vp?Vp:4294967296+Vp}}else NN=0;var a9=NN;0!==a9&&(oa.ifk=a9);var yB=yW(a.pubWin);if(yB&&yB.document){var zB=yB.document,ou=yB;ou=void 0===ou?g.q:ou;var b9=zB.scrollingElement||("CSS1Compat"==zB.compatMode?zB.documentElement:zB.body);var c9=new g.Qd(ou.pageXOffset||b9.scrollLeft,ou.pageYOffset||b9.scrollTop)}else c9=new g.Qd(-12245933,-12245933);var d9=c9;oa.scr_x=Math.round(d9.x);oa.scr_y=Math.round(d9.y);var PN=a.pubWin,Eva=IX.getInstance().C();PN.google_ad_modifications||
(PN.google_ad_modifications={});var QN=PN.google_ad_modifications;QN.eids||(QN.eids=[]);var Fva=Eva.concat(QN.eids).join(",");oa.eid=Fva;var e9=a.C.google_loeid;"string"===typeof e9&&(a.F|=4096,oa.loeid=e9);a.G&&(oa.oid=a.G);var Gva=LX(),f9=MX(Gva,20,{})[a.C.google_ad_client];f9&&(oa.psts=f9.join());var RN=a.pubWin;if("number"!==typeof RN.goog_pvsid)try{Object.defineProperty(RN,"goog_pvsid",{value:Math.floor(Math.random()*Math.pow(2,52))})}catch(Vg){}oa.pvsid=Number(RN.goog_pvsid)||-1;var g9=bY(kB,
a.pubWin);a:{var AB=-1;try{g9&&(AB=parseInt(g9.getItem("goog_pem_mod"),10))}catch(Vg){var h9=null;break a}h9=0<=AB&&1E3>AB?AB:null}oa.pem=h9;if(bX())try{var i9=a.pubWin&&a.pubWin.external&&a.pubWin.external.getHostEnvironmentValue&&a.pubWin.external.getHostEnvironmentValue.bind(a.pubWin.external);if(i9){var j9=parseInt(JSON.parse(i9("os-mode"))["os-mode"],10);0<=j9&&(oa.wsm=j9+1)}}catch(Vg){}var yf=a.C,SN=a.pubWin,pu=a.N,Hva=GW();oa.ref=yf.google_referrer_url;oa.loc=yf.google_page_location;var BB=
AW(SN);if(BB&&g.Ma(BB.data)&&"string"===typeof BB.data.type){var TN=BB.data.type.toLowerCase();var k9="doubleclick"==TN||"adsense"==TN?null:TN}else k9=null;var l9=k9;l9&&(oa.apn=l9.substr(0,10));var qu=HW(Hva);oa.url||oa.loc||!qu.url||(oa.url=qu.url,qu.Qk||(oa.usrc=1));qu.url!=(oa.loc||oa.url)&&(oa.top=qu.url);yf.google_async_rrc&&(oa.rr=yf.google_async_rrc);oa.rx=0;var m9;if(nY&&$X(nY))var n9=nY;else{var UN=GW(),Yi=UN.google_jobrunner;n9=Yi&&(Ioa(Yi)||BW(Yi))&&$X(Yi)&&DW(Yi.nq)&&DW(Yi.nqa)&&DW(Yi.al)&&
DW(Yi.rl)?nY=Yi:UN.google_jobrunner=nY=new YX(UN)}var o9=n9;(m9=DW(o9.tc)?o9.tc():null)&&(oa.jtc=m9);0<=a.D&&(oa.eae=a.D);var Iva=pu?bY(kB,pu):null,p9=vpa(yf,pu,Iva);p9&&(oa.fc=p9);var q9=yf.google_ad_format;if(!(q9&&0<q9.indexOf("_0ads"))){var su=(a.iframeWin||a.pubWin).document,r9="";if(su.documentMode){var Fm=(new g.lr(su)).createElement("IFRAME");Fm.frameBorder="0";Fm.style.height=0;Fm.style.width=0;Fm.style.position="absolute";if(su.body){su.body.appendChild(Fm);try{var CB=Fm.contentWindow.document;
CB.open();CB.write(g.fc(g.Qca));CB.close();r9+=CB.documentMode}catch(Vg){}su.body.removeChild(Fm)}}oa.docm=r9}oa.brdim=g.ve(SN).join();var s9=0;void 0===g.q.postMessage&&(s9|=1);var t9=s9;0<t9&&(oa.osd=t9);oa.vis=g.bg(SN.document);if(!TX(yf)){a:{var tu=Number(yf.google_ad_width),uu=Number(yf.google_ad_height);if(!(0<tu&&0<uu)){b:{try{var VN=String(yf.google_ad_format);if(VN&&VN.match){var WN=VN.match(/(\d+)x(\d+)/i);if(WN){var u9=parseInt(WN[1],10),v9=parseInt(WN[2],10);if(0<u9&&0<v9){var w9={width:u9,
height:v9};break b}}}}catch(Vg){}w9=null}var XN=w9;if(!XN){var x9=null;break a}tu=0<tu?tu:XN.width;uu=0<uu?uu:XN.height}x9={width:tu,height:uu}}var YN=x9;if(YN){var y9=0;a:{try{var z9=yf.google_async_iframe_id,A9=zW().document;if(z9)var B9=A9.getElementById(z9);else{var C9=A9.getElementsByTagName("script"),D9=C9[C9.length-1];B9=D9&&D9.parentNode||null}var E9=B9;if(E9){for(var vu=[],DB=E9,Jva=0,Kva=Date.now();100>=++Jva&&50>Date.now()-Kva&&(DB=Mpa(DB));)1===DB.nodeType&&vu.push(DB);b:{for(var ZN=0;ZN<
vu.length;ZN++){c:{var Zi=vu[ZN];try{if(Zi.parentNode&&0<Zi.offsetWidth&&0<Zi.offsetHeight&&Zi.style&&"none"!==Zi.style.display&&"hidden"!==Zi.style.visibility&&(!Zi.style.opacity||0!==Number(Zi.style.opacity))){var F9=Zi.getBoundingClientRect();var G9=0<F9.right&&0<F9.bottom;break c}}catch(Vg){}G9=!1}if(!G9){var H9=!1;break b}}H9=!0}if(H9){b:{for(var Mva=Date.now(),Nva=/^html|body$/i,Ova=/^fixed/i,$N=0;$N<vu.length&&50>Date.now()-Mva;$N++){var EB=vu[$N];if(!Nva.test(EB.tagName)&&Ova.test(EB.style.position||
g.Cr(EB))){var aO=EB;break b}}aO=null}break a}}}catch(Vg){}aO=null}var bO=aO;bO&&bO.offsetWidth*bO.offsetHeight<=4*YN.width*YN.height&&(y9=1);oa.pfx=y9}}a:{if(.05>Math.random()&&pu)try{var I9=pu.document.getElementsByTagName("head")[0];var J9=I9?Fpa(I9):0;break a}catch(Vg){}J9=0}var K9=J9;0!==K9&&(oa.cms=K9);"r20100101"!==yf.google_lrv&&(oa.alvm=yf.google_lrv||"none");oa.fu=a.F;oa.bc=g.ag();iY();oa.jar=gY[4];var L9=a.C,Pva=L9.google_ad_channel,M9="/pagead/ads?";"ca-pub-6219811747049371"===L9.google_ad_client&&
Npa.test(Pva)&&(M9="/pagead/lopri?");var cO=cX(e8,M9);3===g.bg(a.pubWin.document)&&(a.H=!0,a.L=cO,cO=cX(e8,"/pagead/blank.gif#?"));var dO=Joa(oa,cO+"");c.google_ad_url=dO;var N9=c.google_trust_token_additional_signing_data||{};N9.url=dO;c.google_trust_token_additional_signing_data=N9;return dO},Mpa=function(a){try{if(a.parentNode)return a.parentNode}catch(e){return null}if(9===a.nodeType)a:{try{var b=g.Hq(a);
if(b){var c=b.frameElement;if(c&&wW(b.parent)){var d=c;break a}}}catch(e){}d=null}else d=null;return d},Hpa=function(a,b){var c=a.C;
CW(fX,function(d,e){b[d]=c[e]});
a.C.google_pub_requests_npa&&(b.npa=1);CW(eX,function(d,e){b[d]=c[e]});
CW(gX,function(d,e){b[d]=c[e]});
TX(c)&&(b.fa=SX(c))},oY=function(){this.G=this.C=!1;
this.F=new g.HJ(this);this.H=!1},xY=function(){if(g.H("WATCH_LEGAL_TEXT_ENABLE_AUTOSCROLL")){var a=document.getElementById("watch_companion_legal_text");
a&&(pY=new oY,pY.start(a))}var b=g.H("ADS_DATA",void 0);b&&(qY(),Ppa(b),rY=b,sY=g.eO(),null!=sY&&(sY.addEventListener("onApiChange",Qpa),sY.addEventListener("onReady",Rpa)),b.pyv_ad_tag&&Spa(b),b.use_gut&&(g.jk("//www.googletagservices.com/tag/js/gpt.js"),g.ik("//www.googletagservices.com/tag/js/gpt.js",function(){Tpa(b.gut_vars.tag)})),b.show_afv&&(g.jk("//pagead2.googlesyndication.com/pagead/show_companion_ad.js"),tY(),g.ik("//pagead2.googlesyndication.com/pagead/show_companion_ad.js",Upa),g.Tg("remove_yt_uds")||
g.ik("//www.google.com/jsapi?autoload=%7B%22modules%22%3A%5B%7B%22name%22%3A%22ads%22%2C%22version%22%3A%221%22%2C%22callback%22%3A%22(function()%7B%7D)%22%2C%22packages%22%3A%5B%22content%22%5D%7D%5D%7D")),uY(),vY&&(vY=!1,wY(b)),g.J("watchAdsInit"))},uY=function(){yY&&null!=sY&&null!=sY.getOptions&&null!=sY.getOptions()&&g.Wa(sY.getOptions(),"ad")&&sY.getOption("ad","PAGE_JAVASCRIPT_INITIALIZED",{})},qY=function(){var a=window.Goog_Osd_UnloadAdBlock,b=g.D("google_companion_ad_div");
"function"===typeof a&&null!=b&&a(g.Sq(b))},Ppa=function(a){zY.length=0;
if("afv_vars"in a)for(var b in a.afv_vars)window[b]=a.afv_vars[b],zY.push(b)},Tpa=function(a){"googletag"in window&&googletag&&(googletag.cmd=googletag.cmd||[],googletag.cmd.push(function(){if(AY=googletag.defineSlot(a,[[300,
250],[300,60]],"google_companion_ad_div")){AY.set("ad_type","flash");AY.addService(googletag.companionAds());googletag.enableServices();var b=AY.getSizes();b&&2<=b.length&&(BY=b[0],CY=b[1])}}))},DY=function(a,b){a||(a="");
b||(b=!1);var c=g.D("watch-channel-brand-div");c&&g.hs(c,"collapsible",b);if(c=g.D("google_companion_ad_div"))c.innerHTML=a},EY=function(a){var b=Math.round(1E4*Math.random());
return['<iframe src="',a,'" name="ifr_300x250ad',b,'" id="ifr_300x250ad',b,'" width="300" height="250" marginwidth="0" marginheight="0" hspace="0" vspace="0" frameborder="0" scrolling="no"></iframe>'].join("")},FY=function(a){return!!a.match("/ad_companion.*render=video_wall_companion")},Upa=function(){g.J("showCompanionAdLoaded")},tY=function(){window.google_ad_output="html";
window.google_ad_height="250";window.google_ad_format="300x250_as";window.google_container_id="google_companion_ad_div"},IY=function(){var a=document.getElementById("google_companion_ad_div");
if(a&&(a=a.firstElementChild)){"DIV"==a.nodeName&&(a=a.firstElementChild);try{var b=encodeURIComponent(GY)+","+encodeURIComponent(HY);a.contentWindow.postMessage(b,"*");a.width=370;a.height=null!=GY?210:185}catch(c){}}},JY=function(){var a=document.getElementById("movie_player");
a&&a.pauseVideo()},Spa=function(a){ZW(a.pyv_ad_tag.tag);
a.log_pyv&&KY.push(g.uh(function(){"google_render_ad"in window?g.Wm("pyvls"):g.Wm("pyvlf")},5E3))},wY=function(a){if(!LY){if(!a){if(!rY){vY=!0;
return}a=rY}if(g.Tg("remove_yt_uds")){LY=!0;window.google_ad_client=a.afv_vars.google_ad_client;window.google_page_url=a.afv_vars.google_page_url;window.google_page_location=window.location.href;var b=a.afc_vars,c;for(c in b){var d=b[c];if("no_initial_ads"==c&&d){hX();return}if("format"!=c||g.wb(g.Qp(d)))if("loeid"!=c||g.wb(g.Qp(d))){var e="google_"+c;(eX[e]||fX[e]||gX[e])&&(window[e]=d)}else window.google_loeid=g.Qp(d);else if(d=g.Qp(d),e=d.match(/(\d+)x(\d+)/))window.google_ad_width=e[1],window.google_ad_height=
e[2],window.google_ad_format=d}b=new Goa;cpa(b);window.google_loader_used="yt";(b=Opa(b))&&Vpa(b);hX()}else(b=g.u("google.ads.Ad"))?(LY=!0,new b(a.afv_vars.google_ad_client,"google_companion_ad_div",a.afc_vars)):MY=g.nh(function(){wY(a)},200)}},Vpa=function(a){var b=g.D("google_companion_ad_div");
null!=b&&(a=g.be("IFRAME",{width:window.google_ad_width,height:window.google_ad_height,frameBorder:0,marginWidth:0,marginHeight:0,vpsace:0,hspace:0,allowTransparency:"true",scrolling:"no",src:a,style:{visibility:"visible"}}),b.appendChild(a))},Qpa=function(){uY()},Rpa=function(){yY=!0;
uY()},Wpa=function(a){var b=null;
"transition"in a.style?b="transition-duration":"webkitTransition"in a.style?b="-webkit-transition-duration":"MozTransition"in a.style?b="-moz-transition-duration":"OTransition"in a.style?b="-o-transition-duration":"msTransition"in a.style&&(b="-ms-transition-duration");a=b?(document.defaultView?document.defaultView.getComputedStyle(a,null):document.parentWindow.getComputedStyle(a,null)).getPropertyValue(b):"0";return 1E3*parseFloat(a)},NY=function(){g.Y.call(this);
this.G=this.J=this.H=this.D=null},OY=function(a,b){if(a&&b){var c=g.PQ(a);
g.fe(b);g.Mq(b,c,0)}},PY=function(){g.Y.call(this);
this.H=null;this.G=0;this.M={report:(0,g.v)(this.sF,this),share:(0,g.v)(this.RF,this)}},QY=function(a){a.G&&(g.qh(a.G),a.G=0);
a.Ud&&(a.Ud.dispose(),a.Ud=null)},Xpa=function(a){a.Ud=new g.ZO(a.D,a.J,a.V,null,null,!1,!1,g.H("SHARE_REFERER",void 0),g.H("SHARE_CAPTION",void 0),null,null,null,null,null,g.H("PLAYLIST_INDEX",void 0),null,"metadata",g.H("EVENT_ID",void 0),null,!0);
g.le(a,a.Ud);g.qh(a.G);a.G=g.oh(function(){var b=g.eO().getCurrentTime(),c=Math.floor(b/3600),d=Math.floor(b%3600%60);b=(0<c?c+":":"")+g.rc(Math.floor(b%3600/60),0<c?2:1)+":"+g.rc(d,2);this.Ud.updateTime(b)},1E3)},$pa=function(){if(RY=g.N("mealbar-promo-renderer")){var a=g.N("yt-uix-button-primary",RY);
if(a){var b=g.N("yt-uix-button-blue-text",RY);if(b){var c=g.N("ad-blocker-msg-data");c&&(SY.push(g.I(a,"click",Ypa,!0),g.I(b,"click",Zpa,!0)),g.L(c,"freq-cap"),TY=g.so(),UY("AD_BLOCKER_MESSAGING_EVENT_TYPE_DISPLAYED"))}}}},Ypa=function(){UY("AD_BLOCKER_MESSAGING_EVENT_TYPE_LEARN_HOW");
VY();g.Tr(RY,!1)},Zpa=function(){UY("AD_BLOCKER_MESSAGING_EVENT_TYPE_DISMISSED");
VY();g.Tr(RY,!1)},UY=function(a){var b=g.Ik();
b&&(a={displayPeriodMs:Math.round(g.so()-TY),adBlockerMessagingEventType:a,clientScreenNonce:b},g.Xj("adBlockerMessagingShown",a))},VY=function(){g.lh(SY);
SY.length=0},bqa=function(){var a=g.M("promoted-button-container");
(0,g.E)(a,function(b){a:{var c=g.L(b,"promo-id");var d=g.Ws(b,"promo-impression-cap")||0;var e=g.Ws(b,"promo-impression-delay")||0;if(c&&0<d&&0<e){c="yt-hint-"+c;var f=g.fz(c)||{},k=f.lastSeen;f=f.impressions||0;if(k&&(0,g.Od)()-new Date(k)<1E3*e||f>=d){d=!1;break a}f={lastSeen:(0,g.Od)(),impressions:f+1};g.ez(c,f,2592E3)}d=!0}d?("true"===g.L(b,"promo-visible")&&(d=g.BD.getInstance(),d.om(b),"hidden"!=window.getComputedStyle(b).visibility&&(d.show(b),g.G(b,"hide-hint-on-scroll")&&(d=g.D(g.L(b,"scroll-parent"))||
window,WY.push(g.Ks(d,"scroll",(0,g.v)(aqa,this,b)))))),g.cJ(b)):(b=g.N("generic-promo-impression-logging",b))&&g.T(b,"generic-promo-impression-logging")})},aqa=function(a){g.BD.getInstance().hide(a)},XY=function(a,b){g.Y.call(this,b);
this.Ga=a;this.G=null;this.D=250;this.aa=this.T=this.M=this.V=this.H=this.J=null;this.oa=0},YY=function(a,b,c){for(var d=0;d<a.length;d++)if(g.fe(a[d]),b){var e=g.PQ(b,c);
g.Mq(a[d],e,0)}},eqa=function(){var a=g.N("youthere-data");
ZY=!1;if($Y=g.N("mealbar-promo-renderer"))if(aZ=g.N("yt-dialog-title",$Y))if(bZ=g.N("yt-ytb",$Y))if(cZ=g.N("youthere-conf"))if(dZ=g.N("youthere-pause-msg"))eZ=parseInt(g.L(a,"pause-del"),10),fZ=parseInt(g.L(a,"lact-th"),10),gZ=parseInt(g.L(a,"prompt-del-sec"),10),hZ.push(g.I(bZ,"click",iZ,!0)),jZ.push(g.Ih("player-ad-end",cqa)),jZ.push(g.Ih("yt-ui-dialog-show-complete",dqa)),ZY=kZ=!0},cqa=function(){ZY&&g.Dh()<fZ&&lZ("YOU_THERE_EVENT_TYPE_BELOW_LACT_THRESHOLD")},dqa=function(a){kZ=!1;
var b=$Y;b&&a&&a.F==b&&((a=g.vx())&&Woa(a),g.nh(function(){hZ.push(g.I(document,"scroll",iZ,!0));hZ.push(g.I(document,"click",iZ,!0))},500),mZ=g.nh(fqa,eZ),lZ("YOU_THERE_EVENT_TYPE_PROMPT_SHOWN"))},iZ=function(){kZ=!0;
nZ();if(oZ){var a=document.getElementById("movie_player");a&&a.playVideo()}g.Tr(bZ,!1);a=cZ;g.Oq(a,aZ);a.className=aZ.className;aZ=a;g.nh(gqa,400);lZ("YOU_THERE_EVENT_TYPE_USER_RESPONDED")},nZ=function(){g.ph(mZ);
g.Jh(jZ);g.lh(hZ);jZ.length=hZ.length=0},fqa=function(){if(!kZ){var a=dZ;
g.Oq(a,aZ);a.className=aZ.className;aZ=a;if(a=document.getElementById("movie_player"))a.pauseVideo(),oZ=!0,lZ("YOU_THERE_EVENT_TYPE_PLAYBACK_PAUSED")}},gqa=function(){var a=new g.yI(aZ,1E3);
a.play();a.O("finish",function(){g.Tr($Y,!1)})},lZ=function(a){var b=g.Ik();
b&&(a={clientScreenNonce:b,lactMs:String(g.Dh()),lactThresholdMs:String(fZ),mediaPosSec:gZ,youThereEventType:a},g.Xj("youThere",a))},hqa=function(){-1!=g.Ug("service_worker_push_logged_out_prompt_watches")&&Toa().then(function(a){100<=a||Uoa(a+1)})},pqa=function(){pZ=g.N("toggle-loop",qZ);
qZ=g.D("watch-appbar-playlist");rZ=g.N("playlist-videos-list",qZ);sZ=g.N("shuffle-playlist",qZ);tZ=g.N("next-playlist-list-item",qZ);uZ=g.N("prev-playlist-list-item",qZ);vZ=g.N("playlist-header-content",qZ);wZ="currently-playing";if(qZ&&rZ){var a=g.eO();a&&(xZ=a,a.addEventListener("onReady",yZ));vZ&&(zZ="true"===g.L(vZ,"initial-loop-state"));AZ.push(g.I(pZ,"click",iqa));AZ.push(g.I(sZ,"click",jqa));AZ.push(g.I(tZ,"click",function(b){BZ(b,"bf_next")}));
AZ.push(g.I(uZ,"click",function(b){BZ(b,"bf_prev")}));
AZ.push(g.Is(rZ,kqa));AZ.push(g.U(rZ,"click",lqa,"yt-uix-button-playlist-remove-item"));CZ.push(g.Ih("navigate",mqa));CZ.push(g.Ih("player-state-change",nqa));CZ.push(g.Ih("player-error",oqa));CZ.push(g.Ih("watch-queue-show",function(b){g.Xm()&&(0==b?g.R(qZ,"watch-queue-nav"):g.X(qZ))}));
CZ.push(g.Ih("watch-queue-hide",function(){g.W(qZ);g.T(qZ,"watch-queue-nav")}));
g.Xm()&&XW()&&(0==YW()?g.R(qZ,"watch-queue-nav"):g.X(qZ));g.H("SKIP_TO_NEXT_VIDEO")&&DZ(5);EZ();FZ();GZ()}},MZ=function(a,b){var c=tZ;
if(b){if(!HZ().loop||IZ)return;var d=vZ;if(d){var e=JZ(d,"auto");var f=g.L(d,"autoplay-clicktracking")||""}}else KZ(),e=JZ(c,"next"),f=g.L(c,"clicktracking")||"";f=LZ(a||"bf_next",f,b,e);g.yl(c.href,f)},NZ=function(a){var b=a||"bf_prev";
a=uZ;var c=JZ(a,"prev"),d=g.L(a,"clicktracking")||"";b=LZ(b,d,!1,c);g.yl(a.href,b)},HZ=function(){var a=[],b=-1,c=rZ;
if(!c)return null;(0,g.E)(c.getElementsByTagName("li"),function(e,f){g.G(e,wZ)&&(b=f);var k={encrypted_id:g.L(e,"video-id"),author:g.L(e,"video-username"),title:g.L(e,"video-title"),start:g.L(e,"video-clip-start"),end:g.L(e,"video-clip-end"),iurl:g.L(e,"thumbnail-url")};a.push(k)});
c=vZ;var d=b+1<a.length||zZ;return{author:g.L(c,"list-author"),loop:d,index:b,list:g.L(c,"full-list-id"),title:g.L(c,"list-title"),description:g.L(c,"list-description"),video:a}},FZ=function(){g.J("yt-dom-content-change",rZ)},JZ=function(a,b){var c=g.H("SHUFFLE_VALUE"),d=zZ,e="normal";
c&&d?e="loop_shuffle":c?e="shuffle":d&&(e="loop");return g.L(a,e+"-"+b+"-clicktracking")},yZ=function(a){xZ&&xZ.removeEventListener("onReady",yZ);
xZ=a;a.addEventListener("onCueRangeEnter",OZ);var b=a.getDuration(),c=g.H("PREFETCH_AUTOPLAY"),d=g.H("PREFETCH_AUTOPLAY_TIME",10);c&&a.addCueRange("AUTOPLAY_PREFETCH",b-d,b);g.H("EXP_DEBUG_PREFETCH")&&g.Wm(g.Ec({a:"registerNearEndEventsWithPlayer",endTime:b,prefetchEnabled:c,prefetchTime:d}));a.addEventListener("onPlaylistNext",MZ);a.addEventListener("onPlaylistPrevious",NZ);a.addEventListener("onPlaylistIndex",PZ)},OZ=function(a){if("AUTOPLAY_PREFETCH"==a&&(a=g.H("PREFETCH_AUTOPLAY_TIME",10),HZ().loop&&
!IZ&&!QZ)){QZ=!0;
var b=vZ;if(b){var c=JZ(b,"auto");var d=g.L(b,"autoplay-clicktracking")||""}b=tZ.href;d=LZ("autoplay",d,!0,c,a);g.wG(b,!!g.H("PREBUFFER_AUTOPLAY"),d,qqa)}},qqa=function(a){QZ=!1;
RZ=a.response.cacheKey||null},KZ=function(){RZ&&(spf.cache.remove(RZ),RZ=null)},GZ=function(){g.yh()?(g.vh(SZ),SZ=g.uh(g.w(g.Kh,"watch-list-change"))):g.J("watch-list-change")},DZ=function(a){0==a?MZ("mr_meh",!0):TZ=g.nh(function(){DZ(a-1)},1E3)},UZ=function(){var a=vZ;
return!(!a||"False"==g.L(a,"shareable"))},iqa=function(){var a=pZ;
a&&(zZ=!g.$B.getInstance().isToggled(a))},jqa=function(){var a=rZ,b=g.$a(a.getElementsByTagName("li")),c=sZ;
c&&g.$B.getInstance().isToggled(c)?(b=rqa(b),g.Pg("SHUFFLE_VALUE",0)):(c=sqa(b),b=tqa(b,c));g.fe(a);(0,g.E)(b,function(d){a.appendChild(d)});
c=g.H("SHUFFLE_VALUE");VZ(b,c);EZ();FZ();WZ();GZ()},WZ=function(){var a=rZ,b=g.Eq("li",null,a);
g.N("currently-playing",a);var c=0;(0,g.E)(b,function(d){(d=g.N("index",d))&&!isNaN(d.innerText)&&g.O(d,c+1);c+=1})},kqa=function(a){var b=g.kr(a.currentTarget,"li"),c=g.L(b,"clicktracking")||"";
b=g.L(b,"innertube-clicktracking")||"";XZ(a,void 0,c,b)},BZ=function(a,b){var c=g.L(a.currentTarget,"clicktracking")||"";
XZ(a,b,c)},XZ=function(a,b,c,d){b=LZ(b||"BFa",c,!1,d);
c=a.currentTarget.href;d={};var e=g.H("SHUFFLE_VALUE");e?d.shuffle=e:-1!=c.indexOf("shuffle=")&&(d.shuffle=0);d&&(c=g.ki(c,d));g.lc(a.currentTarget,c);g.wl(c,b);KZ()},lqa=function(a){var b=vZ,c=g.kr(a.currentTarget,"li");
if(b&&c){var d=rZ;g.R(d,"playlist-editing-locked");a=g.L(b,"full-list-id");var e=g.L(c,"video-id"),f=g.Ws(c,"index");g.mD({videoIds:e,fullListId:a,onSuccess:function(){g.Nq(c);var k=g.Eq("li",null,d),l=g.N("currently-playing",d);(0,g.E)(k,function(n){var r=g.Ws(n,"index");r>f&&g.Xs(n,"index",r-1)});
"RD"!=g.L(b,"full-list-id").substring(0,2)&&WZ();l=l&&g.Ws(l,"index")+1||0;var m=g.D("playlist-current-index");m&&g.O(m,l);(l=g.D("playlist-length"))&&g.O(l,k.length);VZ(k,g.H("SHUFFLE_VALUE"))},
Ya:function(){g.T(d,"playlist-editing-locked");GZ()}})}},nqa=function(a){0==a&&MZ("autoplay",!0)},oqa=function(){},mqa=function(){IZ=!0},tqa=function(a,b){function c(f){var k=0,l=[];
for(f=f.split("");f.length;){k=(b+k)%f.length;var m=f[k];g.Ya(f,k);l.push(m)}return l.join("")}
g.cp(a,function(f,k){var l=g.L(f,"video-id"),m=g.L(k,"video-id");return c(l).localeCompare(c(m))});
var d=b>>8,e=g.Ta(a,function(f){f=g.L(f,"index");return d==f})||0;
0<e&&(a=g.Zo(a,e).concat(g.Zo(a,0,e)));return a},rqa=function(a){g.cp(a,function(b,c){var d=g.Ws(b,"index"),e=g.Ws(c,"index");
return d-e});
return a},sqa=function(a){var b=g.H("SHUFFLE_VALUE");
if(!b){var c=0;(0,g.E)(a,function(d){g.G(d,wZ)&&(c=g.L(d,"index"))});
b=(c<<8)+Math.floor(256*Math.random());g.Pg("SHUFFLE_VALUE",b)}return b},VZ=function(a,b){var c=null;
(0,g.E)(a,function(l){g.G(l,wZ)&&(c=l)});
if(c){var d=g.Tq(c);d||(d=a[0]);var e=g.Uq(c);e||(e=a[a.length-1]);var f=tZ,k=uZ;f&&d&&(d={v:g.L(d,"video-id")},b?d.shuffle=b:-1!=f.href.indexOf("shuffle=")&&(d.shuffle=0),g.lc(f,g.ki(f.href,d)));k&&e&&(d={v:g.L(e,"video-id")},b?d.shuffle=b:-1!=k.href.indexOf("shuffle=")&&(d.shuffle=0),g.lc(k,g.ki(k.href,d)))}},LZ=function(a,b,c,d,e){var f={},k=g.H("EVENT_ID");
k&&(f.ei=k,a&&(f.feature=a),d?f.itct=d:b&&(f.ved=b),(a=g.H("SHUFFLE_VALUE"))&&(f.shuffle=a),zZ&&(f.loop_on=!0),c&&(f.playnext=g.H("LIST_AUTO_PLAY_VALUE"),f.autonav=1,c=g.Dh(),0<c&&(f.lact=c),e&&(f.prefetch=e),(e=xZ)&&e.isReady()&&(e=e.getVisibilityState(),0!=e&&(f.vis=e))));return f},EZ=function(){var a=g.N("playlist-videos-list",qZ),b=g.N(wZ,a);
if(b){var c=g.vE.getInstance();if(a&&b){var d=g.M(g.Z(c,"scroll-unit"),a);b=(0,g.Va)(d,b);if(0<=b&&!(!a||isNaN(b)||0>b)&&(c=g.M(g.Z(c,"scroll-unit"),a),!(0>=c.length))){b>=c.length&&(b=c.length-1);if(c.length){d=c[0];var e=d.offsetHeight;1<c.length&&(e=c[1].offsetTop-d.offsetTop);d=e}else d=0;e=a.offsetHeight;b>Math.max(Math.floor(a.scrollTop/d),0)-1&&(d=Math.floor(e/d),e=c.length,b+d>e&&(b=e-d+1));0>b&&(b=0);b=c[b].offsetTop;a&&!isNaN(b)&&(0>b&&(b=0),a.scrollTop=b,g.Xs(a,"scroller-offset",b+""),
g.J("yt-dom-content-change",a))}}}},PZ=function(a){a=g.Qq(rZ)[a];
g.Ws(a,"index");a&&(a=g.N("playlist-video",a))&&a.click()},uqa=function(a){var b=0,c=g.eO();
c&&c.isReady()&&(b=c.getCurrentTime());b=Math.floor(b);var d=Math.floor(b/60);b={action_get_report_video_component:1,video_id:g.H("VIDEO_ID"),t_mins:d,t_secs:b-60*d};"METADATA_LANGUAGE"in g.Og&&(b.metadata_language=g.H("METADATA_LANGUAGE"));c&&c.isReady()&&(c=c.getOption("cc","track")||c.getOption("captions","track"))&&(b.cc_vss_id=c.vss_id);return g.K("/watch_ajax",{method:"GET",Xa:b,onSuccess:function(e,f){a(f.report_html,!0)},
onError:function(){a(null,!1)},
ob:!0})},ZZ=function(a,b){g.F.call(this);
this.N=a;this.F=b;this.J=g.D("watch8-secondary-actions");g.N("like-button-renderer",a);this.D="action-panel-none";this.C=[];this.G=[];this.H=null;this.L=0;this.G.push(g.Ih("player-share",this.Jq,this));this.G.push(g.Ih("livestreaming-likes-updated",this.vG,this));this.C.push(g.U(this.N,"click",(0,g.v)(this.Gq,this),"action-panel-trigger"));this.C.push(g.U(this.F,"click",(0,g.v)(this.Ix,this),"yt-uix-close"));var c=g.D("action-panel-overflow-menu");c&&this.C.push(g.U(c,"click",(0,g.v)(this.Gq,this),
"action-panel-trigger"));c=g.Rs(window.location.hash).action;"share"==c?this.Jq():"flag"==c&&YZ(this,"action-panel-report")},vqa=function(){var a=g.N("yt-uix-button-toggled",g.D("action-panel-share")),b;
UZ()&&a?b=g.L(a,"video-id"):b=g.H("VIDEO_ID",void 0);return b},wqa=function(){var a=null;
if(UZ()){var b=g.D("share-with-playlist");if(!b||b&&b.checked)a=(a=vZ)?g.L(a,"full-list-id"):""}return a},YZ=function(a,b,c,d){var e=g.N("watch-secondary-actions");
vW(g.$B.getInstance(),e);e=g.D(b);var f=xqa(a,e);e&&f&&(g.R(f,"yt-uix-button-toggled"),$Z(a,b,c,d))},$Z=function(a,b,c,d){if("action-panel-none"!=b){var e=g.D(b);
if(e){var f=!!g.L(e,"auth-required");e=!!g.L(e,"panel-loaded");if(f&&!g.H("LOGGED_IN"))a_(a,"action-panel-login");else if(e)a_(a,b);else switch(b){case "action-panel-share":yqa(a,c,d);break;case "action-panel-transcript":zqa(a);break;case "action-panel-add-transcript":b=g.D("action-panel-add-transcript");g.W(g.D("watch-actions-add-transcript"));g.Xs(b,"panel-loaded","true");a_(a,"action-panel-add-transcript");break;case "action-panel-report":Aqa(a)}}}},yqa=function(a,b,c){var d=vqa(),e=wqa(),f=g.D("action-panel-share"),
k=g.D("watch-actions-share-panel"),l=g.H("SHARE_CAPTION",void 0),m=g.H("SHARE_REFERER",void 0),n=g.H("PLAYLIST_INDEX",void 0),r=g.H("EVENT_ID",void 0),x=!!g.H("LIVESTREAMING_NO_SHARE_TIME");
if(g.H("LIVESTREAMING_DEFAULT_BROADCAST")&&-1==document.location.href.indexOf(d))var y=document.location.pathname;var C=new g.ZO(k,d,e,(0,g.v)(a.UD,a),null,b,x,m,l,null,null,null,null,null,n,null,"watch",r,y,c);g.le(a,C);g.qh(a.L);var S=g.oh(function(){var P=g.eO(),pa=g.lx(f);if(P&&P.isReady()&&pa){P=P.getCurrentTime();pa=Math.floor(P/3600);var Ba=Math.floor(P%3600%60);P=(0<pa?pa+":":"")+g.rc(Math.floor(P%3600/60),0<pa?2:1)+":"+g.rc(Ba,2);C.updateTime(P)}else g.qh(S)},1E3);
a.L=S;g.Xs(f,"panel-loaded","true");a_(a,"action-panel-share")},Aqa=function(a){var b,c=!1,d=!1,e=g.D("action-panel-report"),f=(0,g.v)(function(){a_(this,"action-panel-error")},a);
g.ql(g.H("REPORTVIDEO_CSS",void 0));g.ik(g.H("REPORTVIDEO_JS",void 0),(0,g.v)(function(){this.ub()||(c=!0,d&&c&&b_(e,b))},a));
a.H=uqa((0,g.v)(function(k,l){l?(d=!0,b=k,d&&c&&(b_(e,b),e.focus())):f()},a));
g.Xs(e,"panel-loaded","true");a_(a,"action-panel-report")},b_=function(a,b){g.Gp(a,b);
g.u("yt.www.report.reportvideo.init")(!0)},zqa=function(a){var b=g.D("action-panel-transcript");
g.u("yt.www.watch.transcript.open")(function(){g.X("watch-actions-transcript-loading");g.W(g.D("watch-actions-transcript"))});
g.Xs(b,"panel-loaded","true");a_(a,"action-panel-transcript")},a_=function(a,b){var c=g.D(a.D),d=g.D(b),e=a.F;
b==a.D?g.W(c):(g.W(e),a.D=b,g.X(c),g.W(d))},xqa=function(a,b){var c=g.M("action-panel-trigger",a.N);
return g.Ua(c,function(d){d=g.L(d,"trigger-for");return b.id==d})},Gqa=function(){if(c_=g.D("watch7-preview"))g.LH(),d_.push(g.U(c_,"click",Bqa,"watch-queue-preview-playlist-checkbox")),d_.push(g.U(c_,"click",Cqa,"preview-play-now-button")),d_.push(g.U(c_,"click",Dqa,"preview-play-all-now-button")),d_.push(g.U(c_,"click",e_,"preview-addto-queue-button")),d_.push(g.U(c_,"click",Eqa,"preview-addto-queue-button-success")),d_.push(g.U(c_,"click",e_,"preview-addto-queue-button-error")),d_.push(g.U(null,
"click",Fqa,"watch-queue-preview-menu-choice")),f_.push(g.Ih("watch-queue-show",function(){g_()?h_():g.X(c_)})),f_.push(g.Ih("watch-queue-hide",function(){g.cB()||g.X(c_)})),f_.push(g.Ih("watch-queue-update",i_)),f_.push(g.Ih("watch-queue-empty",function(){g_()?h_():g.X(c_)})),g.Sq(c_)&&(g.H("LIST_ID")&&g.hs(c_,"preview-playlist-mode",!0),j_=g.N("preview-play-loading",c_),k_=g.N("preview-play-now-button",c_),l_=g.N("preview-play-all-now-button",c_),m_=g.N("preview-addto-queue-button",c_),n_=g.N("preview-addto-queue-button-success",
c_),o_=g.N("preview-addto-queue-button-error",c_),g.X(j_)),(g_()||p_())&&h_(),q_=!0},p_=function(){if(!WW())return!1;
var a=!g.lx("player-unavailable"),b=g.kz()?g.fz("yt-remote-session-video-id"):"";return a&&!(b==g.H("VIDEO_ID")&&!g.H("LIST_ID"))},h_=function(){if(!g.lx(c_)&&g.Sq(c_)){var a=WW();
if(a){var b=g.N("video-receiver",c_);b&&g.O(b,a.name)}i_();g.X(j_);r_()?(g.X(k_),g.W(l_)):(g.X(l_),g.W(k_));g.W(c_)}},r_=function(){return g.G(c_,"preview-playlist-mode")},i_=function(){if(g.Sq(c_)&&!r_()){var a=g.VH();
a=g.Wa(a,g.H("VIDEO_ID",void 0));g.kx(n_,a);g.kx(m_,!a);g.X(o_)}},Bqa=function(a){g.hs(c_,"preview-playlist-mode",a.currentTarget.checked);
r_()?(g.W(l_),g.W(m_),g.X(n_),g.X(o_),g.X(k_)):(g.W(k_),g.X(l_),i_())},Cqa=function(){g.W(j_);
g.X(k_);g.J("watch-queue-addto-video-play-now",g.H("VIDEO_ID",void 0))},Dqa=function(){g.W(j_);
g.X(l_);g.J("watch-queue-addto-playlist-play-now",g.H("LIST_ID",void 0),g.H("VIDEO_ID",void 0),s_())},e_=function(){var a=g.H("VIDEO_ID",void 0),b=g.H("LIST_ID",void 0),c=s_();
if(r_()){a=function(){g.W(n_);g.X(m_);g.X(o_);g.J("watch-queue-addto-playlist-added")};
var d=function(){g.W(o_);g.X(n_);g.X(m_)};
c?g.PH(c,a,d):g.SH(b,a,d)}else g.PH(a,function(){g.W(n_);g.X(m_);g.X(o_);g.J("watch-queue-addto-video-added")},function(){g.W(o_);
g.X(n_);g.X(m_)})},Eqa=function(){var a=g.H("VIDEO_ID",void 0);
r_()?g.TH(function(){g.W(m_);g.X(n_);g.X(o_);g.J("watch-queue-addto-playlist-removed")},function(){g.W(o_);
g.X(n_);g.X(m_)}):g.RH(a,function(){g.W(m_);
g.X(n_);g.X(o_);g.J("watch-queue-addto-video-removed")},function(){g.W(o_);
g.X(n_);g.X(m_)})},Fqa=function(a){var b=g.L(a.currentTarget,"action");
Hqa[b](a.currentTarget)},g_=function(){var a=!g.lx("player-unavailable"),b=YW();
b=XW()&&0==b;return a&&g.Xm()&&(b||p_())},s_=function(){var a;
(a=g.H("LIST_ID"))?(a=a.substr(0,2),a="PL"!=a&&"RD"!=a):a=!1;if(!a)return null;a=HZ();if(!a)return null;a=a.video;for(var b=[],c=0;c<a.length;c++)b.push(a[c].encrypted_id);return b},u_=function(a){if(!(a.metaKey||a.ctrlKey||t_(a.target)||t_(document.activeElement)||a.event&&!1===a.event.returnValue))switch(a.keyCode){case 191:break;
default:g.Kh("player-unhandled-keydown",a)}},t_=function(a){return a&&("INPUT"==a.tagName||"TEXTAREA"==a.tagName||"SELECT"==a.tagName||"EMBED"==a.tagName||a.isContentEditable)?!0:!1},Oqa=function(){if(!v_){var a=g.u("ytplayer.config");
if(a&&(v_=g.Sl("player-api")||g.Ql("player-api",a))){a=v_;a.addEventListener("onReady",w_);a.addEventListener("onStateChange",x_);a.addEventListener("onVideoProgress",y_);a.addEventListener("SHARE_CLICKED",z_);a.addEventListener("SIZE_CLICKED",A_);a.addEventListener("onError",B_);a.addEventListener("onAdStart",C_);a.addEventListener("onAdComplete",Iqa);a.addEventListener("onAdSkip",Jqa);a.addEventListener("onAdEnd",Kqa);a.addEventListener("onAutonavChangeRequest",D_);a.addEventListener("onAutonavPauseRequest",
E_);a.addEventListener("onFeedbackStartRequest",F_);a.addEventListener("onFeedbackArticleRequest",G_);a.addEventListener("onScreenChanged",H_);a.addEventListener("onLogClientVeCreated",I_);a.addEventListener("onLogServerVeCreated",J_);a.addEventListener("onLogVeClicked",K_);a.addEventListener("onLogVesShown",L_);a.addEventListener("onYpcContentRequest",M_);a.addEventListener("onPlayVideo",N_);a=document.activeElement;var b=g.D("movie_player");a&&a!=document.body||!b||b.focus();O_();P_=g.oh(O_,1E3);
Q_.push(g.Ih("navigate",Lqa));Q_.push(g.Ih("player-unhandled-keydown",Mqa));Q_.push(g.Ih("watch-list-change",Nqa));R_(Roa)}}},Nqa=function(){var a=v_;
if(a&&a.isReady()){var b=HZ();a.updatePlaylist(b)}},Pqa=function(a,b){var c=S_();
if(c){var d=g.Li(c,"").split(",");d=(0,g.Nm)(d,function(e){return 0!=e.indexOf(a)&&!!e.length});
4<=d.length&&d.shift();d.push(a+":"+b);g.Ki(c,d.join(","),1814400)}},Qqa=function(a){var b=S_();
if(b){var c=g.Li(b,"").split(",");c=(0,g.Nm)(c,function(d){return 0!=d.indexOf(a)});
0==c.length?g.Mi(b):g.Ki(b,c.join(","),1814400)}},T_=function(a){var b=g.eO();
if(b&&b.isReady()){a&&g.Pg("RESUME_COOKIE_NAME",a);a=g.H("VIDEO_ID",void 0);var c=b.getDuration();b=Math.floor(b.getCurrentTime());0==c||120>=b||b+120>=c?Qqa(a):Pqa(a,Math.floor(b))}},w_=function(a){U_(a);
V_(a.getPlayerState());var b=g.H("RELATED_PLAYER_ARGS",void 0);a&&a.updateVideoData&&b&&a.updateVideoData(b)},x_=function(a){1==a&&U_(v_);
V_(a);g.J("player-state-change",a)},y_=function(a){g.J("player-video-progress",a)},U_=function(a){a=a.getAvailableQualityLevels();
g.J("player-quality-data-update",a)},B_=function(a){g.J("player-error",a)},A_=function(a){g.Dt();
g.Ki("wide",a?"1":"0",-1);g.J("player-resize",a)},z_=function(){g.J("player-share")},M_=function(a){var b=v_;
b&&b.isReady()&&b.pauseVideo();(b=g.D("watch-checkout-offers"))&&g.Pk(g.FR,new g.XG(b,a))},C_=function(a){g.J("player-ad-start",a)},I_=function(a){var b=a.id,c=g.Ik(),d=g.Gk();
a=a.ve_type;var e=Rqa++;a=new g.Ck({veType:a,veCounter:e,elementIndex:void 0,dataElement:void 0,youtubeData:void 0});W_[b]=a;c&&d&&g.mt(c,d,[a])},H_=function(a){var b=a.csn;
a=a.root_ve_type;if(b&&a&&(g.Lk(b,a),a=g.Gk()))for(var c in W_){var d=W_[c];d&&g.mt(b,a,[d])}},J_=function(a){W_[a.id]=g.it(a.tracking_params)},K_=function(a){var b=g.Ik();
a=W_[a.id];b&&a&&g.jt(b,a,void 0,void 0)},L_=function(a){a=a.ids;
for(var b=g.Ik(),c=0;c<a.length;c++){var d=W_[a[c]];b&&d&&g.lt(b,d)}},Iqa=function(){g.J("player-ad-complete")},Jqa=function(){g.J("player-ad-skip")},Kqa=function(){g.J("player-ad-end")},D_=function(a){g.J("player-autonav-change-request",a)},E_=function(a){g.J("player-autonav-pause-request",a)},R_=function(a){X_?a():(a=g.Ih("player-playback-start",a),Q_.push(a))},Mqa=function(a){var b=v_;
b&&b.handleGlobalKeyDown(a.keyCode,a.shiftKey)},Y_=function(a,b){var c=v_;
if(c&&(q_?!g.lx(c_):!p_())){var d=null!=b?b:!0;c.seekTo(a,!0);d&&window.scroll(0,0);2==c.getPlayerState()&&c.playVideo()}},O_=function(){if(v_&&v_.isReady()){var a=window.location.hash;
if(a!=Z_){Z_=a;a=g.Rs(a);if("t"in a&&a.t!=$_.t){var b=a.t,c=0;-1!=b.indexOf("h")&&(b=b.split("h"),c=3600*b[0],b=b[1]);-1!=b.indexOf("m")&&(b=b.split("m"),c=60*b[0]+c,b=b[1]);-1!=b.indexOf("s")?(b=b.split("s"),c=1*b[0]+c):c=1*b+c;Y_(c,!1)}$_=a}}},Lqa=function(){g.qh(P_)},V_=function(a){X_||1!=a&&2!=a&&0!=a||(X_=!0,g.J("player-playback-start"))},S_=function(){return g.H("RESUME_COOKIE_NAME",void 0)},F_=function(a){g.GF(void 0,a)},G_=function(a){g.IF(a.articleId,a.helpContext,a.productData)},N_=function(a){var b=
g.li("/watch",{v:a.videoId,
list:a.listId});g.zl(b,a.sessionData)},Sqa=function(a,b){var c=g.Fc("/related_ajax",{continuation:a,
action_more_related_videos:1});spf.load(c,{onDone:b})},Tqa=function(a){var b=a.currentTarget.href,c=g.eO();
if(c){var d=g.Qs(b).v;if(g.H("VIDEO_ID")==d)if(d=g.L(a.currentTarget,"secondary-video-url"),0==c.getPlayerState()&&d)g.lc(a.currentTarget,d);else{c=Math.floor(c.getCurrentTime());a=a.currentTarget;c={t:c};d=b.split("#",2);b=d[0];var e=1<d.length?"#"+d[1]:"";d=g.Rs(e);for(var f in c)d[f]=c[f];if(!g.eb(d)){f="!"=="#".charAt(1)?"#".substr(0,2):"#";c=g.Rs("#");for(var k in d)c[k]=d[k];e=f+g.Ec(c)}g.lc(a,b+e)}}},Uqa=function(a){var b=a.currentTarget;
a=g.L(b,"action");if(b&&"replace-enclosing-action"==a){a0(b);a=g.N("service-endpoint-replace-enclosing-action-notification",g.Uq(b));var c=g.JC(b)||b,d=g.Q(c,"related-list-item");(b=g.N("related-item-dismissable",d))&&c&&((c=g.N("related-item-dismissed-container",d))&&a&&(g.fe(c),g.Jq(c,a)),g.X(b),g.W(c),g.W(a),g.er(d,!0),d.focus())}},Vqa=function(a){a=a.currentTarget;
a0(a);a=g.Q(a,"related-list-item");var b=g.N("related-item-dismissable",a);g.W(b);a=g.N("related-item-dismissed-container",a);g.X(a)},a0=function(a){var b=g.L(a,"dismissal-token"),c=g.L(a,"feedback-token");
a={itct:g.L(a,"innertube-clicktracking")};var d="";b?(d="action_dismiss_item",a.dismissal_token=b,g.H("DISMISS_THROUGH_IT")&&(a.it=1)):c&&(d="action_give_feedback",a.feedback_tokens=[c],a.wait_for_response=1);d&&g.K("/feed_change_ajax?"+d+"=1",{method:"POST",onSuccess:function(){},
ia:a,ob:!0})},c0=function(a){return-1!=(b0.get("dismissedEvents",!0)||[]).indexOf(a)},Wqa=function(){var a=d0;
if(!c0(a)){var b=b0.get("dismissedEvents",!0)||[];b.push(a);b0.set("dismissedEvents",b,void 0,!0)}g.X(e0);g.T(document.body,"gaming-event-promo-visible")},Xqa=function(){var a=g.D("live-chat-iframe");
if(a){var b=new g.QQ;b.Sa(a);f0=b}},ara=function(){var a=g.D("player-messages"),b=Yqa=g.N("mealbar-promo-renderer",a);
if(b){var c=g.Nq(b),d=g.D("watch-header")||g.D("watch-metadata-header");d&&d.appendChild(c);g.UI(b);g.cJ(b);g0=new g.DD(b,!1,!1,!0,!0,!0);b=g.N("dismiss-menu-choice",b);h0.push(g.I(b,"click",Zqa,!0))}i0=g.N("mealbar-visibility",a);$qa()},$qa=function(){var a=i0,b=g.L(a,"trigger-condition");
"TRIGGER_CONDITION_POST_AD"==b?((a=g.L(a,"lact-th"))&&(j0=parseInt(a,10)),k0.push(g.Ih("player-ad-end",function(){l0(!0)}))):"TRIGGER_CONDITION_DEFAULT"==b?l0(!1):"TRIGGER_CONDITION_DELAYED"==b&&(a=g.L(a,"prompt-del-sec"))&&(a=parseInt(a,0),0<a&&(m0=g.Ih("player-video-progress",bra),n0=a))},Zqa=function(){g0&&g0.dismiss("cancel")},l0=function(a){if(a&&(a=j0,-1<a&&g.Dh()<a))return;
g0&&g0.show();g.R(i0,"vve-check");g.fy()},bra=function(a){0<n0&&a>n0&&(l0(!1),g.Jh(m0),n0=-1)},o0=function(){this.F=[];
this.C=0;this.F.push(g.Ih("page-resize",this.AC,this));this.F.push(g.Ih("player-resize",this.Bl,this));this.F.push(g.Ih("player-quality-data-update",this.ZC,this));this.F.push(g.Ih("watch-queue-remote-connection",this.Mq,this));g.Xm()&&this.Mq(!0);this.lg()},dra=function(){var a=g.eO();
a&&a.getPlayerState&&1==a.getPlayerState()?g.xG():p0.push(g.Ih("player-state-change",cra))},cra=function(a){1==a&&g.xG()},hra=function(){Oqa();
g.yh()?q0.push(g.th(g.Ct)):R_(g.Ct);var a=g.N("watch-action-buttons"),b=g.N("watch-action-panels");r0=null;a&&b&&(r0=new ZZ(a,b));if(a=g.N("video-metadata-renderer"))s0=new PY,s0.Sa(a);if(a=g.N("like-button-renderer"))t0=new NY,t0.Sa(a);bqa();if(a=g.N("metadata-updateable-viewership"))u0=new XY(g.H("VIDEO_ID"),null),u0.Sa(a);v0=new o0;g.Bh();g.Eo("ytglobal.ytUtilActivityCallback_",function(){g.J("USER_ACTIVE")});
g.I(document,"keydown",u_);era();$pa();g.H("SKIP_RELATED_ADS")||(g.yh()?q0.push(g.uh(xY)):xY());g.N("youthere-data")&&eqa();ara();pqa();w0.push(g.U(g.D("watch7-sidebar"),"click",Tqa,"resumable-list"));w0.push(g.U(document.documentElement,"click",Uqa,"dismiss-menu-choice"));w0.push(g.U(document.documentElement,"click",Vqa,"undo-replace-action"));dra();Gqa();g.to&&(!document.documentMode||8>document.documentMode)&&x0.push(g.U(document.body,"click",fra,"video-thumb"));g.rJ();Xqa();if(e0=g.D("gaming-event-promo-overlay"))if(d0=
e0.getAttribute("data-event-id"))c0(d0)?g.X(e0):(g.W(e0),g.R(document.body,"gaming-event-promo-visible")),y0.push(g.I(g.D("gaming-event-promo-cancel-button"),"click",Wqa));gra();g.LO.init();-1!=g.Ug("service_worker_push_logged_out_prompt_watches")&&R_(hqa)},fra=function(a){g.kr(a.target,"BUTTON")||a.currentTarget.click()},era=function(){var a=g.N("whitelist-alert");
a&&(z0=new g.lO,z0.Sa(a))},gra=function(){var a=g.Qs(window.location.href);
if(window.history.replaceState&&"time_continue"in a||"disable_polymer"in a)a=g.ki(window.location.href,{time_continue:null,disable_polymer:null}),window.history.replaceState(window.history.state,"",a)},ira=function(){var a=["guide"];
A0.guide=g.nh(function(){g.N("guide-module-loading")&&(g.lh(B0.Hv),C0(a,"time",!1))},3E3)},jra=function(a){if(!g.D("watch-sidebar-discussion")){var b=g.D("watch-discussion");
if(g.Vq(b)){g.R(b,"scrolldetect");g.Xs(b,"scrolldetect-callback","comments-delay-load");var c=(0,g.Od)()+1E3;g.nG({"comments-delay-load":function(){var d=c-(0,g.Od)();A0.comments=g.nh(g.w(C0,a,0<d?"time":"scroll"),d)}})}}},C0=function(a,b,c){var d=g.H("VIDEO_ID",void 0);
d||g.Za(a,"comments");if(a&&a.length){var e=g.Qs(window.location.href);e.v=d;e.tr=b;g.Wa(a,"comments")&&g.H("IS_DISTILLER")&&(e.distiller="1",g.H("COMMENTS_TOKEN")?e.ctoken=g.H("COMMENTS_TOKEN"):g.Za(a,"comments"));g.SF(a,c,e,g.w(kra,a))}},kra=function(a){g.Wa(a,"comments")&&(g.LO.init(),(a=g.H("JS_COMMENTS_MODULE_NAMES"))&&spf.script.require(a),g.J("yt-www-comments-page-updated"))};
g.z(xW,g.pd);
var Ipa={"AMP-CAROUSEL":"ac","AMP-FX-FLYING-CARPET":"fc","AMP-LIGHTBOX":"lb","AMP-STICKY-AD":"sa"},FW=null,Noa=[/^https?:\/\/(secure)?pubads\.g\.doubleclick\.net(:\d+)?($|\/)/i,/^https?:\/\/(googleads|adx)\.g\.doubleclick\.net(:\d+)?($|\/)/i,/^https?:\/\/(?!adx)ad.*\.doubleclick\.net(:\d+)?($|\/)/i,/^https?:\/\/(tpc|pagead2)\.googlesyndication\.com(:\d+)?($|\/)/i,/^https?:\/\/www\.googletagservices\.com(:\d+)?($|\/)/i,/^https?:\/\/adservice\.google\.(com?\.)?[a-z]{2,3}(:\d+)?($|\/)/i],lra=/^https?:\/\/(\w|-)+\.cdn\.ampproject\.(net|org)(\?|\/|$)/,
Qoa=[],SW=!1,Rqa=1,TW=null;var D0={},eX=(D0.google_ad_channel="channel",D0.google_ad_type="ad_type",D0.google_ad_format="format",D0.google_color_bg="color_bg",D0.google_color_border="color_border",D0.google_color_link="color_link",D0.google_color_text="color_text",D0.google_color_url="color_url",D0.google_page_url="url",D0.google_allow_expandable_ads="ea",D0.google_ad_section="region",D0.google_cpm="cpm",D0.google_encoding="oe",D0.google_safe="adsafe",D0.google_flash_version="flash",D0.google_font_face="f",D0.google_font_size=
"fs",D0.google_hints="hints",D0.google_ad_host="host",D0.google_ad_host_channel="h_ch",D0.google_ad_host_tier_id="ht_id",D0.google_kw_type="kw_type",D0.google_kw="kw",D0.google_contents="contents",D0.google_targeting="targeting",D0.google_adtest="adtest",D0.google_alternate_color="alt_color",D0.google_alternate_ad_url="alternate_ad_url",D0.google_cust_age="cust_age",D0.google_cust_ch="cust_ch",D0.google_cust_gender="cust_gender",D0.google_cust_interests="cust_interests",D0.google_cust_job="cust_job",
D0.google_cust_l="cust_l",D0.google_cust_lh="cust_lh",D0.google_cust_u_url="cust_u_url",D0.google_cust_id="cust_id",D0.google_language="hl",D0.google_city="gcs",D0.google_country="gl",D0.google_region="gr",D0.google_content_recommendation_ad_positions="ad_pos",D0.google_content_recommendation_columns_num="cr_col",D0.google_content_recommendation_rows_num="cr_row",D0.google_content_recommendation_ui_type="crui",D0.google_content_recommendation_use_square_imgs="cr_sq_img",D0.google_color_line="color_line",
D0.google_disable_video_autoplay="disable_video_autoplay",D0.google_full_width_responsive_allowed="fwr",D0.google_full_width_responsive="fwrattr",D0.efwr="efwr",D0.google_pgb_reactive="pra",D0.google_resizing_allowed="rs",D0.google_resizing_height="rh",D0.google_resizing_width="rw",D0.rpe="rpe",D0.google_responsive_formats="resp_fmts",D0.google_safe_for_responsive_override="sfro",D0.google_video_doc_id="video_doc_id",D0.google_video_product_type="video_product_type",D0.google_webgl_support="wgl",
D0.google_refresh_count="rc",D0),E0={},fX=(E0.google_ad_block="ad_block",E0.google_ad_client="client",E0.google_ad_output="output",E0.google_ad_callback="callback",E0.google_ad_height="h",E0.google_ad_resize="twa",E0.google_ad_slot="slotname",E0.google_ad_unit_key="adk",E0.google_ad_dom_fingerprint="adf",E0.google_ad_width="w",E0.google_captcha_token="captok",E0.google_content_recommendation_columns_num="cr_col",E0.google_content_recommendation_rows_num="cr_row",E0.google_ctr_threshold="ctr_t",E0.google_cust_criteria=
"cust_params",E0.gfwrnwer="fwrn",E0.gfwrnher="fwrnh",E0.google_bfa="bfa",E0.ebfa="ebfa",E0.ebfaca="ebfaca",E0.google_image_size="image_size",E0.google_last_modified_time="lmt",E0.google_loeid="loeid",E0.google_max_num_ads="num_ads",E0.google_max_radlink_len="max_radlink_len",E0.google_mtl="mtl",E0.google_native_settings_key="nsk",E0.google_enable_content_recommendations="ecr",E0.google_num_radlinks="num_radlinks",E0.google_num_radlinks_per_unit="num_radlinks_per_unit",E0.google_pucrd="pucrd",E0.google_reactive_plaf=
"plaf",E0.google_reactive_plat="plat",E0.google_reactive_fba="fba",E0.google_reactive_sra_channels="plach",E0.google_responsive_auto_format="rafmt",E0.armr="armr",E0.google_rl_dest_url="rl_dest_url",E0.google_rl_filtering="rl_filtering",E0.google_rl_mode="rl_mode",E0.google_rt="rt",E0.google_source_type="src_type",E0.google_restrict_data_processing="rdp",E0.google_tag_for_child_directed_treatment="tfcd",E0.google_tag_for_under_age_of_consent="tfua",E0.google_tag_origin="to",E0.google_ad_semantic_area=
"sem",E0.google_tfs="tfs",E0.google_package="pwprc",E0.google_tag_partner="tp",E0.fra="fpla",E0.google_ml_rank="mlr",E0.google_apsail="psa",E0),F0={},gX=(F0.google_core_dbp="dbp",F0.google_lact="lact",F0.google_only_pyv_ads="pyv",F0.google_scs="scs",F0.google_video_url_to_fetch="durl",F0.google_yt_pt="yt_pt",F0.google_yt_up="yt_up",F0);var RX={yN:0,gK:1,hK:2,nK:8,QN:9,hM:10,iM:11,NN:16,UJ:17,TJ:24,PK:25,tJ:26,mJ:27,zt:30,BK:32,EK:40};var qpa={uJ:"google_ads_preview",XJ:"google_mc_lab",jK:"google_anchor_debug",iK:"google_bottom_anchor_debug",INTERSTITIAL:"google_ia_debug",AK:"google_scr_debug",DK:"google_ia_debug_allow_onclick",QM:"googleads",zt:"google_pedestal_debug",JN:"google_resize_debug",RN:"google_shoppable_images_debug",SN:"google_shoppable_images_cookie",TN:"google_shoppable_images_forced",KN:"google_responsive_slot_debug",MN:"google_responsive_slot_preview",LN:"google_responsive_dummy_ad"},G0={},rpa=(G0.google_bottom_anchor_debug=
1,G0.google_anchor_debug=2,G0.google_ia_debug=8,G0.google_resize_debug=16,G0.google_scr_debug=9,G0.googleads=2,G0.google_pedestal_debug=30,G0);g.Ia(aX);jX.prototype.getUrl=function(a,b,c,d){a=a+"//"+b+c;var e=dpa(this)-c.length-d.length;if(0>e)return"";this.C.sort(function(r,x){return r-x});
c=null;b="";for(var f=0;f<this.C.length;f++)for(var k=this.C[f],l=this.F[k],m=0;m<l.length;m++){if(!e){c=null==c?k:c;break}var n=mX(l[m],this.D,",$");if(n){n=b+n;if(e>=n.length){e-=n.length;a+=n;b=this.D;break}this.G&&(b=e,n[b-1]==this.D&&--b,a+=n.substr(0,b),b=this.D,e=0);c=null==c?k:c}}f="";null!=c&&(f=b+"trn="+c);return a+f+d};var H0=null;var uX=g.q.performance,mra=!!(uX&&uX.mark&&uX.measure&&uX.clearMarks),sX=g.Sa(function(){var a;if(a=mra){var b;if(null===H0){H0="";try{a="";try{a=g.q.top.location.hash}catch(c){a=g.q.location.hash}a&&(H0=(b=a.match(/\bdeid=([\d,]+)/))?b[1]:"")}catch(c){}}b=H0;a=!!b.indexOf&&0<=b.indexOf("1337")}return a});
tX.prototype.disable=function(){this.C=!1;this.events!=this.F.google_js_reporting_queue&&(sX()&&(0,g.E)(this.events,vX),this.events.length=0)};
tX.prototype.start=function(a,b){if(!this.C)return null;var c=qX()||pX();c=new epa(a,b,c);var d="goog_"+c.label+"_"+c.uniqueId+"_start";uX&&sX()&&uX.mark(d);return c};
tX.prototype.end=function(a){if(this.C&&"number"===typeof a.value){var b=qX()||pX();a.duration=b-a.value;b="goog_"+a.label+"_"+a.uniqueId+"_end";uX&&sX()&&uX.mark(b);!this.C||2048<this.events.length||this.events.push(a)}};yX.prototype.G=function(a,b,c,d,e){e=e||"jserror";try{var f=new jX;f.G=!0;nX(f,1,"context",a);b.error&&b.meta&&b.id||(b=new iX(b,{message:zX(b)}));b.msg&&nX(f,2,"msg",b.msg.substring(0,512));var k=b.meta||{};if(this.F)try{this.F(k)}catch(C){}if(d)try{d(k)}catch(C){}b=[k];f.C.push(3);f.F[3]=b;var l=LW(),m=new KW(g.q.location.href,g.q,!1);b=null;var n=l.length-1;for(d=n;0<=d;--d){var r=l[d];!b&&lra.test(r.url)&&(b=r);if(r.url&&!r.hp){m=r;break}}r=null;var x=l.length&&l[n].url;0!=m.depth&&x&&(r=l[n]);
var y=new Poa(m,r);y.F&&nX(f,4,"top",y.F.url||"");nX(f,5,"url",y.C.url||"");oX(this.H,e,f,this.D,c)}catch(C){try{oX(this.H,e,{context:"ecmserr",rctx:a,msg:zX(C),url:y&&y.C.url},this.D,c)}catch(S){}}return!0};var xX,AX,rX=zW(),wX=new tX;xX=new function(){var a=void 0===a?g.re:a;this.F="http:"===a.location.protocol?"http:":"https:";this.C=Math.random()};
"number"!==typeof rX.google_srt&&(rX.google_srt=Math.random());var nra=xX,I0=rX.google_srt;0<=I0&&1>=I0&&(nra.C=I0);AX=new yX;
AX.F=function(a){var b=g.re.jerExpIds;if(Array.isArray(b)&&0!==b.length){var c=a.eid;if(c){b=[].concat(g.ja(c.split(",")),g.ja(b));c={};for(var d=0,e=0;e<b.length;){var f=b[e++];var k=f;k=g.Ma(k)?"o"+g.Oa(k):(typeof k).charAt(0)+k;Object.prototype.hasOwnProperty.call(c,k)||(c[k]=!0,b[d++]=f)}b.length=d;a.eid=b.join(",")}else a.eid=b.join(",")}(b=g.re.jerUserAgent)&&(a.useragent=b)};
AX.D=!0;if("complete"==rX.document.readyState)rX.google_measure_js_timing||wX.disable();else if(wX.C){var ora=function(){rX.google_measure_js_timing||wX.disable()},J0=rX;
J0.addEventListener&&J0.addEventListener("load",ora,!1)};var opa=728*1.38;g.Ia(IX);var JX=null,K0={},kpa=(K0[8]="google_prev_ad_formats_by_region",K0[9]="google_prev_ad_slotnames_by_region",K0);var NX=navigator,Jpa=/^\s*_ga=\s*1\.(\d+)[^.]*\.(.*?)\s*$/,Kpa=/^[^=]+=\s*GA1\.(\d+)[^.]*\.(.*?)\s*$/,Lpa=/^\s*_ga=\s*()(amp-[\w.-]{22,64})$/;g.pc("var i=this.id,s=window.google_iframe_oncopy,H=s&&s.handlers,h=H&&H[i],w=this.contentWindow,d;try{d=w.document}catch(e){}if(h&&d&&(!d.body||!d.body.firstChild)){if(h.call){setTimeout(h,0)}else if(h.match){try{h=s.upd(h,i)}catch(e){}w.location.replace(h)}}");var kY={google:1,googlegroups:1,gmail:1,googlemail:1,googleimages:1,googleprint:1},Gpa=/(corp|borg)\.google\.com:\d+$/;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var L0={},tpa=(L0[16]=4,L0[27]=512,L0[26]=128,L0);g.Uc("script");/*

 Copyright 2019 The AMP HTML Authors. All Rights Reserved.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS-IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
var mY={"image-top":0,"image-middle":1,"image-side":2,"text-only":3,"in-article":4};var nY;g.h=YX.prototype;g.h.Fu=function(a,b){0!=this.C||0!=this.G.length||b&&b!=window?this.Gn(a,b):(this.C=2,this.Er(new aY(a,window)))};
g.h.Gn=function(a,b){this.G.push(new aY(a,b||this.F));ZX(this)};
g.h.YE=function(a){this.C=1;if(a){var b=BX(188,(0,g.v)(this.Dr,this,!0));this.D=this.F.setTimeout(b,a)}};
g.h.Dr=function(a){a&&++this.H;1==this.C&&(null!=this.D&&(this.F.clearTimeout(this.D),this.D=null),this.C=0);ZX(this)};
g.h.hG=function(){return!(!window||!Array)};
g.h.uv=function(){return this.H};
g.h.sG=function(){if(0==this.C&&this.G.length){var a=this.G.shift();this.C=2;var b=BX(190,(0,g.v)(this.Er,this,a));a.tg.setTimeout(b,0);ZX(this)}};
g.h.Er=function(a){this.C=0;a.mc()};
YX.prototype.nq=YX.prototype.Fu;YX.prototype.nqa=YX.prototype.Gn;YX.prototype.al=YX.prototype.YE;YX.prototype.rl=YX.prototype.Dr;YX.prototype.sz=YX.prototype.hG;YX.prototype.tc=YX.prototype.uv;eY.prototype.isSupported=function(a){if(0===this.F){if(dY("__gads",a,this.C.document))a=!0;else{var b=this.C.document;b=void 0===b?document:b;g.kq(a,5)&&(new g.Jd(b)).set("GoogleAdServingTest","Good",void 0);if(b="Good"===dY("GoogleAdServingTest",a,this.C.document)){var c=this.C.document;c=void 0===c?document:c;g.kq(a,5)&&(new g.Jd(c)).remove("GoogleAdServingTest")}a=b}this.F=a?2:1}return 2===this.F};var wpa=/^\.google\.(com?\.)?[a-z]{2,3}$/,xpa=/\.(cn|com\.bi|do|sl|ba|by|ma|am)$/,fY=g.q,gY,hY;var Apa=/^blogger$/,Bpa=/^wordpress(.|\s|$)/i,Cpa=/^joomla!/i,Dpa=/^drupal/i,Epa=/\/wp-content\//,ypa=/\/wp-content\/plugins\/advanced-ads/,zpa=/\/wp-content\/themes\/genesis/,jY=/\/wp-content\/plugins\/genesis/;for(var M0="margin-left margin-right padding-left padding-right border-left-width border-right-width".split(" "),N0=0;N0<M0.length;N0++);M0="margin-top margin-bottom padding-top padding-bottom border-top-width border-bottom-width".split(" ");for(var pra=0;pra<M0.length;pra++);var lY=/[+, ]/,Npa=/YtLoPri/;var r0,s0,t0,u0,v0,z0,pY,rY;g.h=oY.prototype;g.h.start=function(a){var b={start:0};b.end=a.scrollHeight-a.clientHeight;b.duration=b.end/3;b.uh="linear";this.D=new g.Ix(a,b);this.C=!0;this.F.O(a,"click",this.kH);this.F.O(a,"mouseover",this.mH);this.F.O(a,"mouseout",this.jH);this.F.O(a,"scroll",this.lH)};
g.h.lH=function(){this.G||this.C||(this.D.pause(),this.G=!0)};
g.h.kH=function(){this.D.pause();this.C=!1;this.G=!0};
g.h.mH=function(){this.D.pause();this.C=!1};
g.h.jH=function(){this.C||this.G||(this.D.play(),this.C=!0)};
g.h.dispose=function(){this.F.removeAll();this.G=this.C=!1;this.D=null;this.H=!0};
g.h.ub=function(){return this.H};var GY="",HY="",KY=[],LY=!1,zY=[],sY=null,vY=!1,MY=0,AY=null,BY=null,CY=null,yY=!1;g.t("yt.www.watch.ads.setAdId",function(a){window.ad_debug=a},void 0);
g.t("yt.www.watch.ads.setCompanion",DY,void 0);g.t("yt.www.watch.ads.showForcedMpu",function(a){var b=EY(a);a=FY(a);DY(b,a)},void 0);
g.t("yt.www.watch.ads.setGutSlotSizes",function(a,b){if(AY){var c=AY.getSizes();g.Vo(c);b&&BY&&c.push(BY);a&&CY&&c.push(CY)}},void 0);
g.t("yt.www.watch.ads.handleSetCompanion",function(a){a=a.replace(";dc_seed=",";kmyd=watch-channel-brand-div;dc_seed=");var b=EY(a);a=FY(a);DY(b,a)},void 0);
g.t("yt.www.watch.ads.handleSetAfvCompanionVars",tY,void 0);g.t("yt.www.watch.ads.companionSetupComplete",IY,void 0);g.t("yt.www.watch.ads.pauseVideo",JY,void 0);g.t("yt.www.watch.ads.loadAfc",wY,void 0);g.t("yt.www.watch.ads.isAfcAdVisible",function(){var a=g.D("google_companion_ad_div");return a?(a=g.Sq(a))&&"IFRAME"==a.tagName?-1!=a.src.indexOf("youtube.com%2Fad_frame"):!1:!1},void 0);
g.t("yt.www.watch.ads.checkInit",uY,void 0);g.t("yt.www.watch.ads.initVideoWallCompanionListeners",function(a,b){GY=a;HY=b;window.addEventListener("message",function(c){"companion-setup-complete"==c.data?IY():"pause-video"==c.data&&JY()},!1)},void 0);
g.t("yt.www.watch.ads.getGlobals",function(){return zY},void 0);
g.t("window.google_ad_request_done",window.wQ,void 0);g.t("yt.www.ads.pyv.pyvWatchAfcCallback",g.dN,void 0);g.t("yt.www.ads.pyv.loadPyvAjax",ZW,void 0);g.t("yt.www.watch.ads.restrictioncookie.spr",function(a){g.nl(a+"mac_204?action_fcts=1");return!0},void 0);
g.t("yt.www.watch.ads.isPromotionShelfSlotExist",function(){return null!=g.D("promotion-shelf")},void 0);
g.t("yt.www.watch.ads.promotionShelfClear",function(){var a=g.D("promotion-shelf");a&&(g.R(a,"hid"),g.fe(a))},void 0);
g.t("yt.www.watch.ads.promotionShelfShow",function(a){var b=g.D("promotion-shelf");b&&(b.appendChild(a),g.T(b,"hid"))},void 0);
g.t("yt.www.watch.ads.addInstreamCompanionWtaUi",function(a){var b=g.D("google_companion_ad_div");if(b){var c=g.N("iv-cards-companion",b)||g.N("iv-website-companion",b)||b;g.R(b,"companion-with-wta");c.appendChild(a)}else g.ah(Error("Cannot find google_companion_ad_div"))},void 0);
g.t("setAfvCompanionVars",tY,void 0);g.z(NY,g.Y);g.h=NY.prototype;
g.h.Z=function(){NY.Y.Z.call(this);this.D=g.N("like-button-renderer-like-button-unclicked",this.K());this.H=g.N("like-button-renderer-like-button-clicked",this.K());this.J=g.N("like-button-renderer-dislike-button-unclicked",this.K());this.G=g.N("like-button-renderer-dislike-button-clicked",this.K());g.L(this.K(),"logged-in")&&(g.NB(this,"click","like-button-renderer-like-button-unclicked",this.Zv),g.NB(this,"click","like-button-renderer-like-button-clicked",this.wo),g.NB(this,"click","like-button-renderer-dislike-button-unclicked",
this.Yv),g.NB(this,"click","like-button-renderer-dislike-button-clicked",this.wo));g.Ih("new-like-renderer-notification",this.uG,this)};
g.h.Ta=function(){NY.Y.Ta.call(this)};
g.h.Zv=function(){g.R(this.D,"hid");g.T(this.H,"hid");g.T(this.J,"hid");g.R(this.G,"hid");g.J("yt-uix-videolike-liked");g.J("watch-video-liked")};
g.h.wo=function(a){g.T(this.D,"hid");g.R(this.H,"hid");g.T(this.J,"hid");g.R(this.G,"hid");g.G(a.target,"like-button-renderer-like-button-clicked")&&g.J("yt-uix-videolike-unliked")};
g.h.Yv=function(){g.G(this.D,"hid")&&g.J("yt-uix-videolike-unliked");g.T(this.D,"hid");g.R(this.H,"hid");g.R(this.J,"hid");g.T(this.G,"hid")};
g.h.uG=function(a){OY(a.likeCountText,this.D);OY(a.likeCountWithLikeText,this.H);OY(a.dislikeCountText,this.J);OY(a.dislikeCountWithDislikeText,this.G)};g.p(PY,g.Y);g.h=PY.prototype;g.h.Z=function(){g.Y.prototype.Z.call(this);this.D=this.R("video-metadata-renderer-panel");this.J=g.L(this.Ld(),"video-id");var a=g.N("playlist-header-content",g.D("watch-appbar-playlist"));this.V=a?g.L(a,"full-list-id"):"";g.NB(this,"click","video-metadata-renderer-button",this.Uv)};
g.h.Ta=function(){g.Y.prototype.Ta.call(this)};
g.h.W=function(){g.Y.prototype.W.call(this);QY(this);this.V=this.J="";this.D=null};
g.h.Uv=function(a){a=g.L(a.currentTarget,"action");a in this.M&&(this.T!=a?(this.M[a](),g.W(this.D),this.T=a):(g.X(this.D),this.D&&g.fe(this.D),QY(this),this.T=null))};
g.h.RF=function(){this.Ud||(Xpa(this),g.KB("share"))};
g.h.sF=function(){this.H||(g.ql(g.H("REPORTVIDEO_CSS",void 0)),g.ik(g.H("REPORTVIDEO_JS",void 0),(0,g.v)(this.ky,this)))};
g.h.ky=function(){var a=0,b=g.eO();b&&b.pauseVideo()&&(b.pauseVideo(),a=b.getCurrentTime());a={action_get_report_video_component:1,video_id:this.J,t_mins:Math.floor(a)/60,t_secs:Math.floor(a)%60};"METADATA_LANGUAGE"in g.Og&&(a.metadata_language=g.H("METADATA_LANGUAGE"));g.K("/watch_ajax",{method:"GET",Xa:a,onSuccess:(0,g.v)(function(c,d){this.H=d.report_html;g.Gp(this.D,this.H);g.u("yt.www.report.reportvideo.init")(!0)},this),
ob:!0})};var RY=null,TY=0,SY=[];var WY=[];g.p(XY,g.Y);g.h=XY.prototype;g.h.ab=function(a){g.Y.prototype.ab.call(this,a);this.ha=a};
g.h.Z=function(){g.Y.prototype.Z.call(this);this.G||(this.G=new g.cg(this.ZE,this.D,this),g.le(this,this.G));this.G.start()};
g.h.Ta=function(){this.G.stop();g.Y.prototype.Ta.call(this)};
g.h.ZE=function(){this.J||(this.J=new g.Wj(void 0));var a={context:g.Wh(this.J.C||g.Xh())};this.H?a.continuation=this.H:a.videoId=this.Ga;var b={timeout:3E4};b.onSuccess=(0,g.v)(this.yx,this);b.onError=(0,g.v)(this.Bk,this);b.Nc=(0,g.v)(this.Bk,this);g.Zh(this.J,"updated_metadata",a,b)};
g.h.yx=function(a){if(this.xb)if(!a||a.error)this.Bk();else{var b=a.continuation;if(b&&b.timedContinuationData){b=b.timedContinuationData;var c=parseInt(b.timeoutMs,10);this.D=!c||0>c?0:c;this.H=b.continuation||null}else this.H=null,this.D=0;0<this.D&&this.G.start(this.D);if(a=a.actions)for(b=0;b<a.length;b++)if(a[b].updateViewershipAction)a:{c=a[b].updateViewershipAction||null;try{var d=c.viewership.videoViewCountRenderer.viewCount;if(!d&&!c.isEmpty)break a}catch(f){break a}null===this.aa&&(this.aa=
g.M("metadata-updateable-viewership"));YY(this.aa,d||null,!1)}else if(a[b].updateDateTextAction)(c=a[b].updateDateTextAction||null)&&c.dateText&&(c=c.dateText,null===this.M&&(this.M=g.M("metadata-updateable-date-text")),YY(this.M,c,!1));else if(a[b].updateDescriptionAction){if((c=a[b].updateDescriptionAction||null)&&c.description){var e=c.description;if(e||c.isEmpty)null===this.T&&(this.T=g.M("metadata-updateable-description")),YY(this.T,e,!0)}}else a[b].updateTitleAction?(c=a[b].updateTitleAction||
null)&&c.title&&(c=c.title,null===this.V&&(this.V=g.M("metadata-updateable-title")),YY(this.V,c,!1)):a[b].updateSentimentAction&&g.J("new-like-renderer-notification",a[b].updateSentimentAction.sentimentRenderer.likeButtonRenderer)}};
g.h.Bk=function(){this.xb&&(this.oa++,3<=this.oa?this.D=0:(this.D=Math.max(6E4,2*this.D),this.G.start(this.D)))};var $Y,aZ,bZ,cZ,dZ,eZ,fZ,gZ,ZY,kZ,mZ,oZ=!1,jZ=[],hZ=[];var AZ=[],CZ=[],SZ=0,xZ=null,IZ=!1,QZ=!1,RZ=null,qZ=null,rZ=null,pZ=null,sZ=null,tZ=null,uZ=null,vZ=null,wZ="",TZ=null,zZ=!1;g.z(ZZ,g.F);g.h=ZZ.prototype;g.h.W=function(){g.lh(this.C);this.C.length=0;g.Jh(this.G);this.G.length=0;g.qh(this.L);this.H&&this.H.abort();ZZ.Y.W.call(this)};
g.h.Jq=function(){YZ(this,"action-panel-share",!1,!0);g.bs(this.F,document.body,!0)};
g.h.Ix=function(){vW(g.$B.getInstance(),this.J);g.X(this.F)};
g.h.Gq=function(a){a=g.L(a.currentTarget,"trigger-for");a==this.D?g.nx(this.F):$Z(this,a,!1,!0);"action-panel-report"==a&&(a=g.eO())&&a.isReady()&&a.pauseVideo()};
g.h.UD=function(){g.X("watch-actions-share-loading")};
g.h.vG=function(a,b,c,d){var e=g.D("watch7-views-info"),f=g.N("likes-count",e);f&&g.O(f,a);(a=g.N("dislikes-count",e))&&g.O(a,b);if(b=g.N("video-extras-sparkbar-likes",e))b.style.width=c+"%";if(c=g.N("video-extras-sparkbar-dislikes",e))c.style.width=d+"%"};var c_,q_,j_,k_,l_,m_,n_,o_,Hqa={"play-next":function(){var a=g.H("VIDEO_ID",void 0),b=g.H("LIST_ID",void 0);r_()?g.J("watch-queue-addto-playlist-play-next",b,a):g.J("watch-queue-addto-video-play-next",a)}},d_=[],f_=[];var v_,Q_=[],X_=!1,Z_="",$_={},P_=0,W_={};var w0=[];g.t("yt.www.watch.related.loadMore",function(a){g.X("watch-more-related-button");g.W("watch-more-related");a=g.L(a,"continuation");Sqa(a,function(){var b=g.D("watch-more-related");g.J("yt-uix-load-more-success");g.J("yt-dom-content-change",b)})},void 0);
g.t("yt.www.watch.player.getClientPlaybackNonce",function(){var a=v_;return a&&a.isReady()?a.getVideoData().cpn||"":""},void 0);
g.t("yt.www.watch.player.seekTo",Y_,void 0);g.t("yt.www.watch.player.pause",function(){var a=v_;a&&a.pauseVideo()},void 0);
g.t("yt.www.watch.player.saveResumeOffset",T_,void 0);g.t("yt.www.watch.lists.loadThumbnails",FZ,void 0);g.t("yt.www.watch.lists.getState",HZ,void 0);g.t("yt.www.watch.lists.next",MZ,void 0);g.t("yt.www.watch.lists.prev",NZ,void 0);var y0=[],e0=null,d0=null,b0=new g.Ni("ytg-eventpromo");var f0=null;var k0=[],h0=[],g0=null,Yqa=null,i0=null,j0=-1,m0=-1,n0=-1;g.h=o0.prototype;g.h.dispose=function(){g.ph(this.C);g.Jh(this.F);this.F.length=0};
g.h.AC=function(){this.lg()};
g.h.Mq=function(a){var b=g.D("page");b&&(b=g.G(b,"watch-wide"),a?b&&this.Bl(!1):"1"!==g.Li("wide")||b||this.Bl(!0))};
g.h.Bl=function(a){a=!!a;var b=g.D("watch7-sidebar"),c=g.D("page");if(g.D("player")&&b&&c){var d=Wpa(b);a?(g.R(c,"watch-wide"),g.J("yt-dom-content-change",b),g.ph(this.C),this.C=g.nh((0,g.v)(function(){this.lg();g.J("yt-dom-content-change")},this),d)):(g.T(c,"watch-wide"),g.R(c,"watch-non-stage-mode"),g.T(c,"watch-stage-mode"),this.lg(),g.J("yt-dom-content-change"),g.ph(this.C),this.C=g.nh(function(){g.J("yt-dom-content-change",b)},d))}};
g.h.ZC=function(a){g.G(document.body,"flexwatch-noupscale")&&((0,g.In)(["large","hd720","hd1080"],function(b){return g.Wa(a,b)}),this.lg())};
g.h.lg=function(){g.ph(this.C);var a=g.D("player"),b=g.D("page");if(g.D("watch7-container")&&a){a=g.G(b,"watch-wide");var c=window.matchMedia&&window.matchMedia("screen and (max-width: 656px)").matches;c?b&&(g.T(b,"watch-stage-mode"),g.R(b,"watch-non-stage-mode")):a&&b&&(g.T(b,"watch-non-stage-mode"),g.R(b,"watch-stage-mode"));(b=g.eO())&&(b.isReady()?b.setSizeStyle(!c,a):b.addEventListener("onReady",(0,g.v)(this.lg,this)))}};var p0=[];var q0=[],x0=[],qra=[];var B0={},A0={};g.il(g.nt({name:"www/watch",deps:["www/common"],page:"watch",init:function(){hra();g.N("guide-module-loading")&&ira();var a=[];g.H("WATCH_COMMENTS_FORCE_DISABLED")||a.push("comments");g.H("DELAY_LOAD_FOOTER")&&a.push("footer");jra(a);g.MI();g.RI()},
dispose:function(){r0&&(g.ke(r0),r0=null);v0&&(g.ke(v0),v0=null);s0&&(g.ke(s0),s0=null);t0&&(g.ke(t0),t0=null);u0&&(g.ke(u0),u0=null);g.Ls(document,"keydown",u_);VY();g.wh(KY);KY.length=0;var a=rY;a&&(a.use_gut&&g.jk("//www.googletagservices.com/tag/js/gpt.js"),a.show_afv&&g.jk("//pagead2.googlesyndication.com/pagead/show_companion_ad.js"));null!=window.adModuleLoaded&&g.Ms("adModuleLoaded");g.ph(MY);sY&&(sY=null);pY&&(pY.dispose(),pY=null);qY();rY=CY=BY=AY=null;yY=vY=LY=!1;if(zY.length){for(a=zY.length-
1;0<=a;a--)g.Ms(zY[a]);zY.length=0}g.YM();nZ();g.Jh(k0);g.Jh(m0);g.lh(h0);k0.length=0;h0.length=0;g.VI();g.dJ();g.lh(AZ);AZ.length=0;a=xZ;xZ=null;a&&(a.removeEventListener("onCueRangeEnter",OZ),a.removeEventListener("onReady",yZ),a.isReady()&&(a.removeCueRange("AUTOPLAY_PREFETCH"),a.removeEventListener("onPlaylistNext",MZ),a.removeEventListener("onPlaylistPrevious",NZ),a.removeEventListener("onPlaylistIndex",PZ)));g.Jh(CZ);CZ.length=0;qZ&&g.T(qZ,"scrolled");QZ=IZ=!1;vZ=uZ=tZ=sZ=rZ=pZ=qZ=RZ=null;wZ=
"";TZ&&(g.ph(TZ),TZ=null);g.vh(SZ);(a=g.D("guide-container"))&&g.T(a,"branded");if(a=g.D("player"))a.style.background="";w0&&(g.lh(w0),w0=[]);g.Jh(p0);p0.length=0;g.Jh(f_);f_.length=0;g.lh(d_);d_.length=0;c_&&(q_=!1,o_=n_=m_=l_=k_=j_=c_=null,g.NH());z0&&z0.dispose();g.lh(x0);x0.length=0;g.Jh(qra);qra.length=0;g.wh(q0);q0.length=0;(a=v_)&&a.sendAbandonmentPing&&a.sendAbandonmentPing();S_()&&T_();g.qh(P_);v_&&(a=v_,a.removeEventListener("onReady",w_),a.removeEventListener("onStateChange",x_),a.removeEventListener("onVideoProgress",
y_),a.removeEventListener("SHARE_CLICKED",z_),a.removeEventListener("SIZE_CLICKED",A_),a.removeEventListener("onError",B_),a.removeEventListener("onAdStart",C_),a.removeEventListener("onAutonavChangeRequest",D_),a.removeEventListener("onAutonavPauseRequest",E_),a.removeEventListener("onFeedbackStartRequest",F_),a.removeEventListener("onFeedbackArticleRequest",G_),a.removeEventListener("onScreenChanged",H_),a.removeEventListener("onLogClientVeCreated",I_),a.removeEventListener("onLogServerVeCreated",
J_),a.removeEventListener("onLogVeClicked",K_),a.removeEventListener("onLogVesShown",L_),a.removeEventListener("onYpcContentRequest",M_),a.removeEventListener("onPlayVideo",N_));v_=null;X_=!1;Z_="";$_={};g.Jh(Q_);Q_.length=0;W_={};g.wJ();g.ke(f0);f0=null;g.dJ();g.lh(WY);for(a=WY.length=0;a<y0.length;a++)g.lh(y0[a]);document.body&&g.T(document.body,"gaming-event-promo-visible");g.LO.dispose();for(var b in A0)g.ph(A0[b]);A0={};g.lh(B0.Hv);g.LO.dispose();g.SE(g.OI)}}));})(_yt_www);
